setfenv(1, WhatsTraining)

OverridenSpells["HUNTER"] = {
}

ClassSpellsByLevel["HUNTER"] = {
	[1] = {
		{id=1494, name="Track Beasts", subText="", level=1, icon="Interface\\Icons\\Ability_Tracking", school="Survival", cost=10},
	},
	[4] = {
		{id=13163, name="Aspect of the Monkey", subText="", level=4, icon="Interface\\Icons\\Ability_Hunter_AspectOfTheMonkey", school="Beast Mastery", cost=100},
		{id=1978, name="Serpent Sting", subText="Rank 1", level=4, icon="Interface\\Icons\\Ability_Hunter_Quickshot", school="Marksmanship", cost=100},
	},
	[6] = {
		{id=3044, name="Arcane Shot", subText="Rank 1", level=6, icon="Interface\\Icons\\Ability_ImpalingBolt", school="Marksmanship", cost=100},
		{id=1130, name="Hunter's Mark", subText="Rank 1", level=6, icon="Interface\\Icons\\Ability_Hunter_SniperShot", school="Marksmanship", cost=100},
	},
	[8] = {
		{id=5116, name="Concussive Shot", subText="", level=8, icon="Interface\\Icons\\Spell_Frost_Stun", school="Marksmanship", cost=200},
		{id=3127, name="Parry", subText="", level=8, icon="Interface\\Icons\\Ability_Parry", school="Beast Mastery", cost=200},
		{id=14260, name="Raptor Strike", subText="Rank 2", level=8, icon="Interface\\Icons\\Ability_MeleeDamage", school="Survival", cost=200},
	},
	[10] = {
		{id=13165, name="Aspect of the Hawk", subText="Rank 1", level=10, icon="Interface\\Icons\\Spell_Nature_RavenForm", school="Beast Mastery", cost=400},
		{id=4187, name="Great Stamina", subText="Rank 1", level=10, icon="Interface\\Icons\\Spell_Natur e_UnyeildingStamina", school="Pet Training", cost=10},
		{id=24545, name="Natural Armor", subText="Rank 1", level=10, icon="Interface\\Icons\\Spell_Natu re_SpiritArmor", school="Pet Training", cost=10},
		{id=13549, name="Serpent Sting", subText="Rank 2", level=10, icon="Interface\\Icons\\Ability_Hunter_Quickshot", school="Marksmanship", cost=400, requiredIds={1978}},
		{id=19883, name="Track Humanoids", subText="", level=10, icon="Interface\\Icons\\Spell_Holy_PrayerOfHealing", school="Survival", cost=400},
	},
	[12] = {
		{id=14281, name="Arcane Shot", subText="Rank 2", level=12, icon="Interface\\Icons\\Ability_ImpalingBolt", school="Marksmanship", cost=600, requiredIds={3044}},
		{id=20736, name="Distracting Shot", subText="Rank 1", level=12, icon="Interface\\Icons\\Spell_Arcane_Blink", school="Marksmanship", cost=600},
		{id=4188, name="Great Stamina", subText="Rank 2", level=12, icon="Interface\\Icons\\Spell_Natur e_UnyeildingStamina", school="Pet Training", cost=120},
		{id=136, name="Mend Pet", subText="Rank 1", level=12, icon="Interface\\Icons\\Ability_Hunter_MendPet", school="Beast Mastery", cost=600, requiredIds={1515}},
		{id=24549, name="Natural Armor", subText="Rank 2", level=12, icon="Interface\\Icons\\Spell_Natu re_SpiritArmor", school="Pet Training", cost=120},
		{id=2974, name="Wing Clip", subText="Rank 1", level=12, icon="Interface\\Icons\\Ability_Rogue_Trip", school="Survival", cost=600},
	},
	[14] = {
		{id=6197, name="Eagle Eye", subText="", level=14, icon="Interface\\Icons\\Ability_Hunter_EagleEye", school="Beast Mastery", cost=1200},
		{id=1002, name="Eyes of the Beast", subText="", level=14, icon="Interface\\Icons\\Ability_EyeOfTheOwl", school="Beast Mastery", cost=1200},
		{id=1513, name="Scare Beast", subText="Rank 1", level=14, icon="Interface\\Icons\\Ability_Druid_Cower", school="Beast Mastery", cost=1200},
	},
	[16] = {
		{id=13795, name="Immolation Trap", subText="Rank 1", level=16, icon="Interface\\Icons\\Spell_Fire_FlameShock", school="Survival", cost=1800},
		{id=1495, name="Mongoose Bite", subText="Rank 1", level=16, icon="Interface\\Icons\\Ability_Hunter_SwiftStrike", school="Survival", cost=1800},
		{id=14261, name="Raptor Strike", subText="Rank 3", level=16, icon="Interface\\Icons\\Ability_MeleeDamage", school="Survival", cost=1800, requiredIds={14260}},
	},
	[18] = {
		{id=14318, name="Aspect of the Hawk", subText="Rank 2", level=18, icon="Interface\\Icons\\Spell_Nature_RavenForm", school="Beast Mastery", cost=2000, requiredIds={13165}},
		{id=4189, name="Great Stamina", subText="Rank 3", level=18, icon="Interface\\Icons\\Spell_Natur e_UnyeildingStamina", school="Pet Training", cost=400},
		{id=2643, name="Multi-Shot", subText="Rank 1", level=18, icon="Interface\\Icons\\Ability_UpgradeMoonGlaive", school="Marksmanship", cost=2000},
		{id=24550, name="Natural Armor", subText="Rank 3", level=18, icon="Interface\\Icons\\Spell_Natu re_SpiritArmor", school="Pet Training", cost=400},
		{id=13550, name="Serpent Sting", subText="Rank 3", level=18, icon="Interface\\Icons\\Ability_Hunter_Quickshot", school="Marksmanship", cost=2000, requiredIds={13549}},
		{id=19884, name="Track Undead", subText="", level=18, icon="Interface\\Icons\\Spell_Shadow_DarkSummoning", school="Survival", cost=2000},
	},
	[20] = {
		{id=24493, name="Arcane Resistance", subText="Rank 1", level=20, icon="Interface\\Icons\\Spell_ Nature_StarFall", school="Pet Training", cost=440},
		{id=14282, name="Arcane Shot", subText="Rank 3", level=20, icon="Interface\\Icons\\Ability_ImpalingBolt", school="Marksmanship", cost=2200, requiredIds={14281}},
		{id=5118, name="Aspect of the Cheetah", subText="", level=20, icon="Interface\\Icons\\Ability_Mount_JungleTiger", school="Beast Mastery", cost=2200},
		{id=781, name="Disengage", subText="Rank 1", level=20, icon="Interface\\Icons\\Ability_Rogue_Feint", school="Survival", cost=2200},
		{id=14274, name="Distracting Shot", subText="Rank 2", level=20, icon="Interface\\Icons\\Spell_Arcane_Blink", school="Marksmanship", cost=2200, requiredIds={20736}},
		{id=674, name="Dual Wield", subText="", level=20, icon="Interface\\Icons\\Ability_DualWield", school="Beast Mastery", cost=2200},
		{id=23992, name="Fire Resistance", subText="Rank 1", level=20, icon="Interface\\Icons\\Spell_Fi re_FireArmor", school="Pet Training", cost=440},
		{id=1499, name="Freezing Trap", subText="Rank 1", level=20, icon="Interface\\Icons\\Spell_Frost_ChainsOfIce", school="Survival", cost=2200},
		{id=24446, name="Frost Resistance", subText="Rank 1", level=20, icon="Interface\\Icons\\Spell_F rost_FrostWard", school="Pet Training", cost=440},
		{id=14917, name="Growl", subText="Rank 3", level=20, icon="Interface\\Icons\\Ability_Physical_T aunt", school="Pet Training", cost=440},
		{id=3111, name="Mend Pet", subText="Rank 2", level=20, icon="Interface\\Icons\\Ability_Hunter_MendPet", school="Beast Mastery", cost=2200, requiredIds={136}},
		{id=24492, name="Nature Resistance", subText="Rank 1", level=20, icon="Interface\\Icons\\Spell_ Nature_ResistNature", school="Pet Training", cost=440},
		{id=24488, name="Shadow Resistance", subText="Rank 1", level=20, icon="Interface\\Icons\\Spell_ Shadow_AntiShadow", school="Pet Training", cost=40},
	},
	[22] = {
		{id=14323, name="Hunter's Mark", subText="Rank 2", level=22, icon="Interface\\Icons\\Ability_Hunter_SniperShot", school="Marksmanship", cost=6000, requiredIds={1130}},
		{id=3043, name="Scorpid Sting", subText="", level=22, icon="Interface\\Icons\\Ability_Hunter_CriticalShot", school="Marksmanship", cost=6000},
	},
	[24] = {
		{id=1462, name="Beast Lore", subText="", level=24, icon="Interface\\Icons\\Ability_Physical_Taunt", school="Beast Mastery", cost=7000},
		{id=4190, name="Great Stamina", subText="Rank 4", level=24, icon="Interface\\Icons\\Spell_Natur e_UnyeildingStamina", school="Pet Training", cost=1260},
		{id=24551, name="Natural Armor", subText="Rank 4", level=24, icon="Interface\\Icons\\Spell_Natu re_SpiritArmor", school="Pet Training", cost=1260},
		{id=14262, name="Raptor Strike", subText="Rank 4", level=24, icon="Interface\\Icons\\Ability_MeleeDamage", school="Survival", cost=7000, requiredIds={14261}},
		{id=19885, name="Track Hidden", subText="", level=24, icon="Interface\\Icons\\Ability_Stealth", school="Survival", cost=7000},
	},
	[26] = {
		{id=14302, name="Immolation Trap", subText="Rank 2", level=26, icon="Interface\\Icons\\Spell_Fire_FlameShock", school="Survival", cost=7000, requiredIds={13795}},
		{id=3045, name="Rapid Fire", subText="", level=26, icon="Interface\\Icons\\Ability_Hunter_RunningShot", school="Marksmanship", cost=7000},
		{id=13551, name="Serpent Sting", subText="Rank 4", level=26, icon="Interface\\Icons\\Ability_Hunter_Quickshot", school="Marksmanship", cost=7000, requiredIds={13550}},
		{id=19880, name="Track Elementals", subText="", level=26, icon="Interface\\Icons\\Spell_Frost_SummonWaterElemental", school="Survival", cost=7000},
	},
	[28] = {
		{id=14283, name="Arcane Shot", subText="Rank 4", level=28, icon="Interface\\Icons\\Ability_ImpalingBolt", school="Marksmanship", cost=8000, requiredIds={14282}},
		{id=14319, name="Aspect of the Hawk", subText="Rank 3", level=28, icon="Interface\\Icons\\Spell_Nature_RavenForm", school="Beast Mastery", cost=8000, requiredIds={14318}},
		{id=13809, name="Frost Trap", subText="", level=28, icon="Interface\\Icons\\Spell_Frost_FreezingBreath", school="Survival", cost=8000},
		{id=3661, name="Mend Pet", subText="Rank 3", level=28, icon="Interface\\Icons\\Ability_Hunter_MendPet", school="Beast Mastery", cost=8000, requiredIds={3111}},
	},
	[30] = {
		{id=24497, name="Arcane Resistance", subText="Rank 2", level=30, icon="Interface\\Icons\\Spell_ Nature_StarFall", school="Pet Training", cost=1440},
		{id=13161, name="Aspect of the Beast", subText="", level=30, icon="Interface\\Icons\\Ability_Mount_PinkTiger", school="Beast Mastery", cost=8000},
		{id=15629, name="Distracting Shot", subText="Rank 3", level=30, icon="Interface\\Icons\\Spell_Arcane_Blink", school="Marksmanship", cost=8000, requiredIds={14274}},
		{id=5384, name="Feign Death", subText="", level=30, icon="Interface\\Icons\\Ability_Rogue_FeignDeath", school="Survival", cost=8000},
		{id=24439, name="Fire Resistance", subText="Rank 2", level=30, icon="Interface\\Icons\\Spell_Fi re_FireArmor", school="Pet Training", cost=1440},
		{id=24447, name="Frost Resistance", subText="Rank 2", level=30, icon="Interface\\Icons\\Spell_F rost_FrostWard", school="Pet Training", cost=1440},
		{id=4191, name="Great Stamina", subText="Rank 5", level=30, icon="Interface\\Icons\\Spell_Natur e_UnyeildingStamina", school="Pet Training", cost=1440},
		{id=14918, name="Growl", subText="Rank 4", level=30, icon="Interface\\Icons\\Ability_Physical_T aunt", school="Pet Training", cost=1440},
		{id=14269, name="Mongoose Bite", subText="Rank 2", level=30, icon="Interface\\Icons\\Ability_Hunter_SwiftStrike", school="Survival", cost=8000, requiredIds={1495}},
		{id=14288, name="Multi-Shot", subText="Rank 2", level=30, icon="Interface\\Icons\\Ability_UpgradeMoonGlaive", school="Marksmanship", cost=8000, requiredIds={2643}},
		{id=24552, name="Natural Armor", subText="Rank 5", level=30, icon="Interface\\Icons\\Spell_Natu re_SpiritArmor", school="Pet Training", cost=1440},
		{id=24502, name="Nature Resistance", subText="Rank 2", level=30, icon="Interface\\Icons\\Spell_ Nature_ResistNature", school="Pet Training", cost=1440},
		{id=14326, name="Scare Beast", subText="Rank 2", level=30, icon="Interface\\Icons\\Ability_Druid_Cower", school="Beast Mastery", cost=8000, requiredIds={1513}},
		{id=24505, name="Shadow Resistance", subText="Rank 2", level=30, icon="Interface\\Icons\\Spell_ Shadow_AntiShadow", school="Pet Training", cost=1440},
	},
	[32] = {
		{id=1543, name="Flare", subText="", level=32, icon="Interface\\Icons\\Spell_Fire_Flare", school="Marksmanship", cost=10000},
		{id=14263, name="Raptor Strike", subText="Rank 5", level=32, icon="Interface\\Icons\\Ability_MeleeDamage", school="Survival", cost=10000, requiredIds={14262}},
		{id=14275, name="Scorpid Sting", subText="Rank 2", level=32, icon="Interface\\Icons\\Ability_Hu nter_CriticalShot", school="Marksmanship", cost=10000, requiredIds={3043}},
		{id=19878, name="Track Demons", subText="", level=32, icon="Interface\\Icons\\Spell_Shadow_SummonFelHunter", school="Survival", cost=10000},
	},
	[34] = {
		{id=14272, name="Disengage", subText="Rank 2", level=34, icon="Interface\\Icons\\Ability_Rogue_Feint", school="Survival", cost=12000, requiredIds={781}},
		{id=13813, name="Explosive Trap", subText="Rank 1", level=34, icon="Interface\\Icons\\Spell_Fire_SelfDestruct", school="Survival", cost=12000},
		{id=13552, name="Serpent Sting", subText="Rank 5", level=34, icon="Interface\\Icons\\Ability_Hunter_Quickshot", school="Marksmanship", cost=12000, requiredIds={13551}},
	},
	[36] = {
		{id=14284, name="Arcane Shot", subText="Rank 5", level=36, icon="Interface\\Icons\\Ability_ImpalingBolt", school="Marksmanship", cost=14000, requiredIds={14283}},
		{id=4192, name="Great Stamina", subText="Rank 6", level=36, icon="Interface\\Icons\\Spell_Natur e_UnyeildingStamina", school="Pet Training", cost=2520},
		{id=14303, name="Immolation Trap", subText="Rank 3", level=36, icon="Interface\\Icons\\Spell_Fire_FlameShock", school="Survival", cost=14000, requiredIds={14302}},
		{id=3662, name="Mend Pet", subText="Rank 4", level=36, icon="Interface\\Icons\\Ability_Hunter_MendPet", school="Beast Mastery", cost=14000, requiredIds={3661}},
		{id=24553, name="Natural Armor", subText="Rank 6", level=36, icon="Interface\\Icons\\Spell_Natu re_SpiritArmor", school="Pet Training", cost=2520},
		{id=3034, name="Viper Sting", subText="Rank 1", level=36, icon="Interface\\Icons\\Ability_Hunter_AimedShot", school="Marksmanship", cost=14000},
	},
	[38] = {
		{id=14320, name="Aspect of the Hawk", subText="Rank 4", level=38, icon="Interface\\Icons\\Spell_Nature_RavenForm", school="Beast Mastery", cost=16000, requiredIds={14319}},
		{id=14267, name="Wing Clip", subText="Rank 2", level=38, icon="Interface\\Icons\\Ability_Rogue_Trip", school="Survival", cost=16000, requiredIds={2974}},
	},
	[40] = {
		{id=24500, name="Arcane Resistance", subText="Rank 3", level=40, icon="Interface\\Icons\\Spell_ Nature_StarFall", school="Pet Training", cost=3240},
		{id=13159, name="Aspect of the Pack", subText="", level=40, icon="Interface\\Icons\\Ability_Mount_WhiteTiger", school="Beast Mastery", cost=18000},
		{id=15630, name="Distracting Shot", subText="Rank 4", level=40, icon="Interface\\Icons\\Spell_Arcane_Blink", school="Marksmanship", cost=18000, requiredIds={15629}},
		{id=24444, name="Fire Resistance", subText="Rank 3", level=40, icon="Interface\\Icons\\Spell_Fi re_FireArmor", school="Pet Training", cost=3240},
		{id=14310, name="Freezing Trap", subText="Rank 2", level=40, icon="Interface\\Icons\\Spell_Frost_ChainsOfIce", school="Survival", cost=18000, requiredIds={1499}},
		{id=24448, name="Frost Resistance", subText="Rank 3", level=40, icon="Interface\\Icons\\Spell_F rost_FrostWard", school="Pet Training", cost=3240},
		{id=14919, name="Growl", subText="Rank 5", level=40, icon="Interface\\Icons\\Ability_Physical_T aunt", school="Pet Training", cost=3240},
		{id=14324, name="Hunter's Mark", subText="Rank 3", level=40, icon="Interface\\Icons\\Ability_Hunter_SniperShot", school="Marksmanship", cost=18000, requiredIds={14323}},
		{id=8737, name="Mail", subText="", level=40, icon="Interface\\Icons\\INV_Chest_Chain_05", school="Beast Mastery", cost=18000},
		{id=24503, name="Nature Resistance", subText="Rank 3", level=40, icon="Interface\\Icons\\Spell_ Nature_ResistNature", school="Pet Training", cost=3240},
		{id=14264, name="Raptor Strike", subText="Rank 6", level=40, icon="Interface\\Icons\\Ability_MeleeDamage", school="Survival", cost=18000, requiredIds={14263}},
		{id=24506, name="Shadow Resistance", subText="Rank 3", level=40, icon="Interface\\Icons\\Spell_ Shadow_AntiShadow", school="Pet Training", cost=3240},
		{id=19882, name="Track Giants", subText="", level=40, icon="Interface\\Icons\\Ability_Racial_Avatar", school="Survival", cost=18000},
		{id=1510, name="Volley", subText="Rank 1", level=40, icon="Interface\\Icons\\Ability_Marksmanship", school="Marksmanship", cost=18000},
	},
	[42] = {
		{id=20909, name="Counterattack", subText="Rank 2", level=42, icon="Interface\\Icons\\Ability_Warrior_Challange", school="Survival", cost=1200, requiredIds={19306}, requiredTalent={name="Talent 19306", tabIndex=1}},
		{id=4193, name="Great Stamina", subText="Rank 7", level=42, icon="Interface\\Icons\\Spell_Natur e_UnyeildingStamina", school="Pet Training", cost=4320},
		{id=14289, name="Multi-Shot", subText="Rank 3", level=42, icon="Interface\\Icons\\Ability_UpgradeMoonGlaive", school="Marksmanship", cost=24000, requiredIds={14288}},
		{id=24554, name="Natural Armor", subText="Rank 7", level=42, icon="Interface\\Icons\\Spell_Natu re_SpiritArmor", school="Pet Training", cost=4320},
		{id=14276, name="Scorpid Sting", subText="Rank 3", level=42, icon="Interface\\Icons\\Ability_Hu nter_CriticalShot", school="Marksmanship", cost=24000, requiredIds={14275}},
		{id=13553, name="Serpent Sting", subText="Rank 6", level=42, icon="Interface\\Icons\\Ability_Hunter_Quickshot", school="Marksmanship", cost=24000, requiredIds={13552}},
	},
	[44] = {
		{id=14285, name="Arcane Shot", subText="Rank 6", level=44, icon="Interface\\Icons\\Ability_ImpalingBolt", school="Marksmanship", cost=26000, requiredIds={14284}},
		{id=14316, name="Explosive Trap", subText="Rank 2", level=44, icon="Interface\\Icons\\Spell_Fire_SelfDestruct", school="Survival", cost=26000, requiredIds={13813}},
		{id=13542, name="Mend Pet", subText="Rank 5", level=44, icon="Interface\\Icons\\Ability_Hunter_MendPet", school="Beast Mastery", cost=26000, requiredIds={3662}},
		{id=14270, name="Mongoose Bite", subText="Rank 3", level=44, icon="Interface\\Icons\\Ability_Hunter_SwiftStrike", school="Survival", cost=26000, requiredIds={14269}},
	},
	[46] = {
		{id=20043, name="Aspect of the Wild", subText="Rank 1", level=46, icon="Interface\\Icons\\Spell_Nature_ProtectionformNature", school="Beast Mastery", cost=28000},
		{id=14304, name="Immolation Trap", subText="Rank 4", level=46, icon="Interface\\Icons\\Spell_Fire_FlameShock", school="Survival", cost=28000, requiredIds={14303}},
		{id=14327, name="Scare Beast", subText="Rank 3", level=46, icon="Interface\\Icons\\Ability_Druid_Cower", school="Beast Mastery", cost=28000, requiredIds={14326}},
		{id=14279, name="Viper Sting", subText="Rank 2", level=46, icon="Interface\\Icons\\Ability_Hunter_AimedShot", school="Marksmanship", cost=28000, requiredIds={3034}},
	},
	[48] = {
		{id=14321, name="Aspect of the Hawk", subText="Rank 5", level=48, icon="Interface\\Icons\\Spell_Nature_RavenForm", school="Beast Mastery", cost=32000, requiredIds={14320}},
		{id=14273, name="Disengage", subText="Rank 3", level=48, icon="Interface\\Icons\\Ability_Rogue_Feint", school="Survival", cost=32000, requiredIds={14272}},
		{id=4194, name="Great Stamina", subText="Rank 8", level=48, icon="Interface\\Icons\\Spell_Natur e_UnyeildingStamina", school="Pet Training", cost=5760},
		{id=24555, name="Natural Armor", subText="Rank 8", level=48, icon="Interface\\Icons\\Spell_Natu re_SpiritArmor", school="Pet Training", cost=5760},
		{id=14265, name="Raptor Strike", subText="Rank 7", level=48, icon="Interface\\Icons\\Ability_MeleeDamage", school="Survival", cost=32000, requiredIds={14264}},
	},
	[50] = {
		{id=24501, name="Arcane Resistance", subText="Rank 4", level=50, icon="Interface\\Icons\\Spell_ Nature_StarFall", school="Pet Training", cost=6480},
		{id=15631, name="Distracting Shot", subText="Rank 5", level=50, icon="Interface\\Icons\\Spell_Arcane_Blink", school="Marksmanship", cost=36000, requiredIds={15630}},
		{id=24445, name="Fire Resistance", subText="Rank 4", level=50, icon="Interface\\Icons\\Spell_Fi re_FireArmor", school="Pet Training", cost=6480},
		{id=24449, name="Frost Resistance", subText="Rank 4", level=50, icon="Interface\\Icons\\Spell_F rost_FrostWard", school="Pet Training", cost=6480},
		{id=14920, name="Growl", subText="Rank 6", level=50, icon="Interface\\Icons\\Ability_Physical_T aunt", school="Pet Training", cost=6480},
		{id=24504, name="Nature Resistance", subText="Rank 4", level=50, icon="Interface\\Icons\\Spell_ Nature_ResistNature", school="Pet Training", cost=6480},
		{id=13554, name="Serpent Sting", subText="Rank 7", level=50, icon="Interface\\Icons\\Ability_Hunter_Quickshot", school="Marksmanship", cost=36000, requiredIds={13553}},
		{id=24507, name="Shadow Resistance", subText="Rank 4", level=50, icon="Interface\\Icons\\Spell_ Shadow_AntiShadow", school="Pet Training", cost=6480},
		{id=19879, name="Track Dragonkin", subText="", level=50, icon="Interface\\Icons\\INV_Misc_Head_Dragon_01", school="Survival", cost=36000},
		{id=14294, name="Volley", subText="Rank 2", level=50, icon="Interface\\Icons\\Ability_Marksmanship", school="Marksmanship", cost=36000, requiredIds={1510}},
		{id=24132, name="Wyvern Sting", subText="Rank 2", level=50, icon="Interface\\Icons\\INV_Spear_02", school="Survival", cost=1800, requiredIds={19386}, requiredTalent={name="Wyvern Sting", tabIndex=1}},
	},
	[52] = {
		{id=14286, name="Arcane Shot", subText="Rank 7", level=52, icon="Interface\\Icons\\Ability_ImpalingBolt", school="Marksmanship", cost=40000, requiredIds={14285}},
		{id=13543, name="Mend Pet", subText="Rank 6", level=52, icon="Interface\\Icons\\Ability_Hunter_MendPet", school="Beast Mastery", cost=40000, requiredIds={13542}},
		{id=14277, name="Scorpid Sting", subText="Rank 4", level=52, icon="Interface\\Icons\\Ability_Hu nter_CriticalShot", school="Marksmanship", cost=40000, requiredIds={14276}},
	},
	[54] = {
		{id=20910, name="Counterattack", subText="Rank 3", level=54, icon="Interface\\Icons\\Ability_Warrior_Challange", school="Survival", cost=2100, requiredIds={20909}, requiredTalent={name="Talent 19306", tabIndex=1}},
		{id=14317, name="Explosive Trap", subText="Rank 3", level=54, icon="Interface\\Icons\\Spell_Fire_SelfDestruct", school="Survival", cost=42000, requiredIds={14316}},
		{id=5041, name="Great Stamina", subText="Rank 9", level=54, icon="Interface\\Icons\\Spell_Natur e_UnyeildingStamina", school="Pet Training", cost=7560},
		{id=14290, name="Multi-Shot", subText="Rank 4", level=54, icon="Interface\\Icons\\Ability_UpgradeMoonGlaive", school="Marksmanship", cost=42000, requiredIds={14289}},
		{id=24629, name="Natural Armor", subText="Rank 9", level=54, icon="Interface\\Icons\\Spell_Natu re_SpiritArmor", school="Pet Training", cost=7560},
	},
	[56] = {
		{id=20190, name="Aspect of the Wild", subText="Rank 2", level=56, icon="Interface\\Icons\\Spell_Nature_ProtectionformNature", school="Beast Mastery", cost=46000, requiredIds={20043}},
		{id=14305, name="Immolation Trap", subText="Rank 5", level=56, icon="Interface\\Icons\\Spell_Fire_FlameShock", school="Survival", cost=46000, requiredIds={14304}},
		{id=14266, name="Raptor Strike", subText="Rank 8", level=56, icon="Interface\\Icons\\Ability_MeleeDamage", school="Survival", cost=46000, requiredIds={14265}},
		{id=14280, name="Viper Sting", subText="Rank 3", level=56, icon="Interface\\Icons\\Ability_Hunter_AimedShot", school="Marksmanship", cost=46000, requiredIds={14279}},
	},
	[58] = {
		{id=14322, name="Aspect of the Hawk", subText="Rank 6", level=58, icon="Interface\\Icons\\Spell_Nature_RavenForm", school="Beast Mastery", cost=48000, requiredIds={14321}},
		{id=14325, name="Hunter's Mark", subText="Rank 4", level=58, icon="Interface\\Icons\\Ability_Hunter_SniperShot", school="Marksmanship", cost=48000, requiredIds={14324}},
		{id=14271, name="Mongoose Bite", subText="Rank 4", level=58, icon="Interface\\Icons\\Ability_Hunter_SwiftStrike", school="Survival", cost=48000, requiredIds={14270}},
		{id=13555, name="Serpent Sting", subText="Rank 8", level=58, icon="Interface\\Icons\\Ability_Hunter_Quickshot", school="Marksmanship", cost=48000, requiredIds={13554}},
		{id=14295, name="Volley", subText="Rank 3", level=58, icon="Interface\\Icons\\Ability_Marksmanship", school="Marksmanship", cost=48000, requiredIds={14294}},
	},
	[60] = {
		{id=14287, name="Arcane Shot", subText="Rank 8", level=60, icon="Interface\\Icons\\Ability_ImpalingBolt", school="Marksmanship", cost=50000, requiredIds={14286}},
		{id=15632, name="Distracting Shot", subText="Rank 6", level=60, icon="Interface\\Icons\\Spell_Arcane_Blink", school="Marksmanship", cost=50000, requiredIds={15631}},
		{id=14311, name="Freezing Trap", subText="Rank 3", level=60, icon="Interface\\Icons\\Spell_Frost_ChainsOfIce", school="Survival", cost=50000, requiredIds={14310}},
		{id=5042, name="Great Stamina", subText="Rank 10", level=60, icon="Interface\\Icons\\Spell_Natu re_UnyeildingStamina", school="Pet Training", cost=9000},
		{id=14921, name="Growl", subText="Rank 7", level=60, icon="Interface\\Icons\\Ability_Physical_T aunt", school="Pet Training", cost=9000},
		{id=13544, name="Mend Pet", subText="Rank 7", level=60, icon="Interface\\Icons\\Ability_Hunter_MendPet", school="Beast Mastery", cost=50000, requiredIds={13543}},
		{id=24630, name="Natural Armor", subText="Rank 10", level=60, icon="Interface\\Icons\\Spell_Nat ure_SpiritArmor", school="Pet Training", cost=9000},
		{id=14268, name="Wing Clip", subText="Rank 3", level=60, icon="Interface\\Icons\\Ability_Rogue_Trip", school="Survival", cost=50000, requiredIds={14267}},
		{id=24133, name="Wyvern Sting", subText="Rank 3", level=60, icon="Interface\\Icons\\INV_Spear_02", school="Survival", cost=2500, requiredIds={24132}, requiredTalent={name="Wyvern Sting", tabIndex=1}},
	},
}
