setfenv(1, WhatsTraining)

OverridenSpells["MAGE"] = {
}

ClassSpellsByLevel["MAGE"] = {
	[1] = {
		{id=1459, name="Arcane Intellect", subText="Rank 1", level=1, icon="Interface\\Icons\\Spell_Holy_MagicalSentry", school="Arcane", cost=10},
	},
	[4] = {
		{id=5504, name="Conjure Water", subText="Rank 1", level=4, icon="Interface\\Icons\\INV_Drink_06", school="Arcane", cost=100},
		{id=116, name="Frostbolt", subText="Rank 1", level=4, icon="Interface\\Icons\\Spell_Frost_FrostBolt02", school="Frost", cost=100},
	},
	[6] = {
		{id=587, name="Conjure Food", subText="Rank 1", level=6, icon="Interface\\Icons\\INV_Misc_Food_10", school="Arcane", cost=100},
		{id=2136, name="Fire Blast", subText="Rank 1", level=6, icon="Interface\\Icons\\Spell_Fire_Fireball", school="Fire", cost=100},
		{id=143, name="Fireball", subText="Rank 2", level=6, icon="Interface\\Icons\\Spell_Fire_FlameBolt", school="Fire", cost=100, requiredIds={133}},
	},
	[8] = {
		{id=5143, name="Arcane Missiles", subText="Rank 1", level=8, icon="Interface\\Icons\\Spell_Nature_StarFall", school="Arcane", cost=200},
		{id=205, name="Frostbolt", subText="Rank 2", level=8, icon="Interface\\Icons\\Spell_Frost_FrostBolt02", school="Frost", cost=200, requiredIds={116}},
		{id=118, name="Polymorph", subText="Rank 1", level=8, icon="Interface\\Icons\\Spell_Nature_Polymorph", school="Arcane", cost=200},
	},
	[10] = {
		{id=5505, name="Conjure Water", subText="Rank 2", level=10, icon="Interface\\Icons\\INV_Drink_07", school="Arcane", cost=400, requiredIds={5504}},
		{id=7300, name="Frost Armor", subText="Rank 2", level=10, icon="Interface\\Icons\\Spell_Frost_FrostArmor02", school="Frost", cost=400, requiredIds={168}},
		{id=122, name="Frost Nova", subText="Rank 1", level=10, icon="Interface\\Icons\\Spell_Frost_FrostNova", school="Frost", cost=400},
	},
	[12] = {
		{id=597, name="Conjure Food", subText="Rank 2", level=12, icon="Interface\\Icons\\INV_Misc_Food_09", school="Arcane", cost=600, requiredIds={587}},
		{id=604, name="Dampen Magic", subText="", level=12, icon="Interface\\Icons\\Spell_Nature_AbolishMagic", school="Arcane", cost=600},
		{id=145, name="Fireball", subText="Rank 3", level=12, icon="Interface\\Icons\\Spell_Fire_FlameBolt", school="Fire", cost=600, requiredIds={143}},
		{id=130, name="Slow Fall", subText="", level=12, icon="Interface\\Icons\\Spell_Magic_FeatherFall", school="Arcane", cost=600},
	},
	[14] = {
		{id=1449, name="Arcane Explosion", subText="Rank 1", level=14, icon="Interface\\Icons\\Spell_Nature_WispSplode", school="Arcane", cost=900},
		{id=1460, name="Arcane Intellect", subText="Rank 2", level=14, icon="Interface\\Icons\\Spell_Holy_MagicalSentry", school="Arcane", cost=900, requiredIds={1459}},
		{id=2137, name="Fire Blast", subText="Rank 2", level=14, icon="Interface\\Icons\\Spell_Fire_Fireball", school="Fire", cost=900, requiredIds={2136}},
		{id=837, name="Frostbolt", subText="Rank 3", level=14, icon="Interface\\Icons\\Spell_Frost_FrostBolt02", school="Frost", cost=900, requiredIds={205}},
	},
	[16] = {
		{id=5144, name="Arcane Missiles", subText="Rank 2", level=16, icon="Interface\\Icons\\Spell_Nature_StarFall", school="Arcane", cost=1500, requiredIds={5143}},
		{id=2855, name="Detect Magic", subText="", level=16, icon="Interface\\Icons\\Spell_Holy_Dizzy", school="Arcane", cost=1500},
		{id=2120, name="Flamestrike", subText="Rank 1", level=16, icon="Interface\\Icons\\Spell_Fire_SelfDestruct", school="Fire", cost=1500},
	},
	[18] = {
		{id=1008, name="Amplify Magic", subText="", level=18, icon="Interface\\Icons\\Spell_Holy_FlashHeal", school="Arcane", cost=1800},
		{id=3140, name="Fireball", subText="Rank 4", level=18, icon="Interface\\Icons\\Spell_Fire_FlameBolt", school="Fire", cost=1800, requiredIds={145}},
		{id=475, name="Remove Lesser Curse", subText="", level=18, icon="Interface\\Icons\\Spell_Nature_RemoveCurse", school="Arcane", cost=1800},
	},
	[20] = {
		{id=1953, name="Blink", subText="", level=20, icon="Interface\\Icons\\Spell_Arcane_Blink", school="Arcane", cost=2000},
		{id=10, name="Blizzard", subText="Rank 1", level=20, icon="Interface\\Icons\\Spell_Frost_IceStorm", school="Frost", cost=2000},
		{id=5506, name="Conjure Water", subText="Rank 3", level=20, icon="Interface\\Icons\\INV_Drink_Milk_02", school="Arcane", cost=2000, requiredIds={5505}},
		{id=12051, name="Evocation", subText="", level=20, icon="Interface\\Icons\\Spell_Nature_Purge", school="Arcane", cost=2000},
		{id=543, name="Fire Ward", subText="Rank 1", level=20, icon="Interface\\Icons\\Spell_Fire_FireArmor", school="Fire", cost=2000},
		{id=7301, name="Frost Armor", subText="Rank 3", level=20, icon="Interface\\Icons\\Spell_Frost_FrostArmor02", school="Frost", cost=2000, requiredIds={7300}},
		{id=7322, name="Frostbolt", subText="Rank 4", level=20, icon="Interface\\Icons\\Spell_Frost_FrostBolt02", school="Frost", cost=2000, requiredIds={837}},
		{id=1463, name="Mana Shield", subText="Rank 1", level=20, icon="Interface\\Icons\\Spell_Shadow_DetectLesserInvisibility", school="Arcane", cost=2000},
		{id=12824, name="Polymorph", subText="Rank 2", level=20, icon="Interface\\Icons\\Spell_Nature_Polymorph", school="Arcane", cost=2000, requiredIds={118}},
		{id=3562, name="Teleport: Ironforge", subText="", level=20, icon="Interface\\Icons\\Spell_Arcane_ TeleportIronForge", school="Arcane", cost=2000, faction="Alliance"},
		{id=3567, name="Teleport: Orgrimmar", subText="", level=20, icon="Interface\\Icons\\Spell_Arcane_ TeleportOrgrimmar", school="Arcane", cost=2000, faction="Horde"},
		{id=3561, name="Teleport: Stormwind", subText="", level=20, icon="Interface\\Icons\\Spell_Arcane_ TeleportStormWind", school="Arcane", cost=2000, faction="Alliance"},
		{id=3563, name="Teleport: Undercity", subText="", level=20, icon="Interface\\Icons\\Spell_Arcane_ TeleportUnderCity", school="Arcane", cost=2000, faction="Horde"},
	},
	[22] = {
		{id=8437, name="Arcane Explosion", subText="Rank 2", level=22, icon="Interface\\Icons\\Spell_Nature_WispSplode", school="Arcane", cost=3000, requiredIds={1449}},
		{id=990, name="Conjure Food", subText="Rank 3", level=22, icon="Interface\\Icons\\INV_Misc_Food_12", school="Arcane", cost=3000, requiredIds={597}},
		{id=2138, name="Fire Blast", subText="Rank 3", level=22, icon="Interface\\Icons\\Spell_Fire_Fireball", school="Fire", cost=3000, requiredIds={2137}},
		{id=6143, name="Frost Ward", subText="Rank 1", level=22, icon="Interface\\Icons\\Spell_Frost_FrostWard", school="Frost", cost=3000},
		{id=2948, name="Scorch", subText="Rank 1", level=22, icon="Interface\\Icons\\Spell_Fire_SoulBurn", school="Fire", cost=3000},
	},
	[24] = {
		{id=5145, name="Arcane Missiles", subText="Rank 3", level=24, icon="Interface\\Icons\\Spell_Nature_StarFall", school="Arcane", cost=4000, requiredIds={5144}},
		{id=2139, name="Counterspell", subText="", level=24, icon="Interface\\Icons\\Spell_Frost_IceShock", school="Arcane", cost=4000},
		{id=8450, name="Dampen Magic", subText="Rank 2", level=24, icon="Interface\\Icons\\Spell_Nature_A bolishMagic", school="Arcane", cost=4000, requiredIds={604}},
		{id=8400, name="Fireball", subText="Rank 5", level=24, icon="Interface\\Icons\\Spell_Fire_FlameBolt", school="Fire", cost=4000, requiredIds={3140}},
		{id=2121, name="Flamestrike", subText="Rank 2", level=24, icon="Interface\\Icons\\Spell_Fire_SelfDestruct", school="Fire", cost=4000, requiredIds={2120}},
		{id=12505, name="Pyroblast", subText="Rank 2", level=24, icon="Interface\\Icons\\Spell_Fire_Fireb all02", school="Fire", cost=200, requiredIds={11366}, requiredTalent={name="Pyroblast", tabIndex=2}},
	},
	[26] = {
		{id=120, name="Cone of Cold", subText="Rank 1", level=26, icon="Interface\\Icons\\Spell_Frost_Glacier", school="Frost", cost=5000},
		{id=865, name="Frost Nova", subText="Rank 2", level=26, icon="Interface\\Icons\\Spell_Frost_FrostNova", school="Frost", cost=5000, requiredIds={122}},
		{id=8406, name="Frostbolt", subText="Rank 5", level=26, icon="Interface\\Icons\\Spell_Frost_FrostBolt02", school="Frost", cost=5000, requiredIds={7322}},
	},
	[28] = {
		{id=1461, name="Arcane Intellect", subText="Rank 3", level=28, icon="Interface\\Icons\\Spell_Holy_MagicalSentry", school="Arcane", cost=7000, requiredIds={1460}},
		{id=6141, name="Blizzard", subText="Rank 2", level=28, icon="Interface\\Icons\\Spell_Frost_IceStorm", school="Frost", cost=7000, requiredIds={10}},
		{id=759, name="Conjure Mana Agate", subText="", level=28, icon="Interface\\Icons\\INV_Misc_Gem_Emerald_01", school="Arcane", cost=7000},
		{id=8494, name="Mana Shield", subText="Rank 2", level=28, icon="Interface\\Icons\\Spell_Shadow_DetectLesserInvisibility", school="Arcane", cost=7000, requiredIds={1463}},
		{id=8444, name="Scorch", subText="Rank 2", level=28, icon="Interface\\Icons\\Spell_Fire_SoulBurn", school="Fire", cost=7000, requiredIds={2948}},
	},
	[30] = {
		{id=8455, name="Amplify Magic", subText="Rank 2", level=30, icon="Interface\\Icons\\Spell_Holy_Fl ashHeal", school="Arcane", cost=8000, requiredIds={1008}},
		{id=8438, name="Arcane Explosion", subText="Rank 3", level=30, icon="Interface\\Icons\\Spell_Nature_WispSplode", school="Arcane", cost=8000, requiredIds={8437}},
		{id=6127, name="Conjure Water", subText="Rank 4", level=30, icon="Interface\\Icons\\INV_Drink_10", school="Arcane", cost=8000, requiredIds={5506}},
		{id=8412, name="Fire Blast", subText="Rank 4", level=30, icon="Interface\\Icons\\Spell_Fire_Fireball", school="Fire", cost=8000, requiredIds={2138}},
		{id=8457, name="Fire Ward", subText="Rank 2", level=30, icon="Interface\\Icons\\Spell_Fire_FireArmor", school="Fire", cost=8000, requiredIds={543}},
		{id=8401, name="Fireball", subText="Rank 6", level=30, icon="Interface\\Icons\\Spell_Fire_FlameBolt", school="Fire", cost=8000, requiredIds={8400}},
		{id=7302, name="Ice Armor", subText="Rank 1", level=30, icon="Interface\\Icons\\Spell_Frost_FrostArmor02", school="Frost", cost=8000},
		{id=12522, name="Pyroblast", subText="Rank 3", level=30, icon="Interface\\Icons\\Spell_Fire_Fireb all02", school="Fire", cost=400, requiredIds={12505}, requiredTalent={name="Pyroblast", tabIndex=2}},
		{id=3565, name="Teleport: Darnassus", subText="", level=30, icon="Interface\\Icons\\Spell_Arcane_ TeleportDarnassus", school="Arcane", cost=8000, faction="Alliance"},
		{id=3566, name="Teleport: Thunder Bluff", subText="", level=30, icon="Interface\\Icons\\Spell_Arc ane_TeleportThunderBluff", school="Arcane", cost=8000, faction="Horde"},
	},
	[32] = {
		{id=8416, name="Arcane Missiles", subText="Rank 4", level=32, icon="Interface\\Icons\\Spell_Nature_StarFall", school="Arcane", cost=10000, requiredIds={5145}},
		{id=6129, name="Conjure Food", subText="Rank 4", level=32, icon="Interface\\Icons\\INV_Misc_Food_08", school="Arcane", cost=10000, requiredIds={990}},
		{id=8422, name="Flamestrike", subText="Rank 3", level=32, icon="Interface\\Icons\\Spell_Fire_SelfDestruct", school="Fire", cost=10000, requiredIds={2121}},
		{id=8461, name="Frost Ward", subText="Rank 2", level=32, icon="Interface\\Icons\\Spell_Frost_FrostWard", school="Frost", cost=10000, requiredIds={6143}},
		{id=8407, name="Frostbolt", subText="Rank 6", level=32, icon="Interface\\Icons\\Spell_Frost_FrostBolt02", school="Frost", cost=10000, requiredIds={8406}},
	},
	[34] = {
		{id=8492, name="Cone of Cold", subText="Rank 2", level=34, icon="Interface\\Icons\\Spell_Frost_Glacier", school="Frost", cost=12000, requiredIds={120}},
		{id=6117, name="Mage Armor", subText="Rank 1", level=34, icon="Interface\\Icons\\Spell_MageArmor", school="Arcane", cost=13000},
		{id=8445, name="Scorch", subText="Rank 3", level=34, icon="Interface\\Icons\\Spell_Fire_SoulBurn", school="Fire", cost=12000, requiredIds={8444}},
	},
	[36] = {
		{id=13018, name="Blast Wave", subText="Rank 2", level=36, icon="Interface\\Icons\\Spell_Holy_Exco rcism_02", school="Fire", cost=650, requiredIds={11113}, requiredTalent={name="Blast Wave", tabIndex=2}},
		{id=8427, name="Blizzard", subText="Rank 3", level=36, icon="Interface\\Icons\\Spell_Frost_IceStorm", school="Frost", cost=13000, requiredIds={6141}},
		{id=8451, name="Dampen Magic", subText="Rank 3", level=36, icon="Interface\\Icons\\Spell_Nature_A bolishMagic", school="Arcane", cost=15000, requiredIds={8450}},
		{id=8402, name="Fireball", subText="Rank 7", level=36, icon="Interface\\Icons\\Spell_Fire_FlameBolt", school="Fire", cost=13000, requiredIds={8401}},
		{id=8495, name="Mana Shield", subText="Rank 3", level=36, icon="Interface\\Icons\\Spell_Shadow_DetectLesserInvisibility", school="Arcane", cost=13000, requiredIds={8494}},
		{id=12523, name="Pyroblast", subText="Rank 4", level=36, icon="Interface\\Icons\\Spell_Fire_Fireb all02", school="Fire", cost=650, requiredIds={12522}, requiredTalent={name="Pyroblast", tabIndex=2}},
	},
	[38] = {
		{id=8439, name="Arcane Explosion", subText="Rank 4", level=38, icon="Interface\\Icons\\Spell_Nature_WispSplode", school="Arcane", cost=14000, requiredIds={8438}},
		{id=3552, name="Conjure Mana Jade", subText="", level=38, icon="Interface\\Icons\\INV_Misc_Gem_Emerald_02", school="Arcane", cost=14000, requiredIds={759}},
		{id=8413, name="Fire Blast", subText="Rank 5", level=38, icon="Interface\\Icons\\Spell_Fire_Fireball", school="Fire", cost=14000, requiredIds={8412}},
		{id=8408, name="Frostbolt", subText="Rank 7", level=38, icon="Interface\\Icons\\Spell_Frost_FrostBolt02", school="Frost", cost=14000, requiredIds={8407}},
	},
	[40] = {
		{id=8417, name="Arcane Missiles", subText="Rank 5", level=40, icon="Interface\\Icons\\Spell_Nature_StarFall", school="Arcane", cost=15000, requiredIds={8416}},
		{id=10138, name="Conjure Water", subText="Rank 5", level=40, icon="Interface\\Icons\\INV_Drink_09", school="Arcane", cost=15000, requiredIds={6127}},
		{id=8458, name="Fire Ward", subText="Rank 3", level=40, icon="Interface\\Icons\\Spell_Fire_FireArmor", school="Fire", cost=15000, requiredIds={8457}},
		{id=8423, name="Flamestrike", subText="Rank 4", level=40, icon="Interface\\Icons\\Spell_Fire_SelfDestruct", school="Fire", cost=15000, requiredIds={8422}},
		{id=6131, name="Frost Nova", subText="Rank 3", level=40, icon="Interface\\Icons\\Spell_Frost_FrostNova", school="Frost", cost=15000, requiredIds={865}},
		{id=7320, name="Ice Armor", subText="Rank 2", level=40, icon="Interface\\Icons\\Spell_Frost_FrostArmor02", school="Frost", cost=15000, requiredIds={7302}},
		{id=12825, name="Polymorph", subText="Rank 3", level=40, icon="Interface\\Icons\\Spell_Nature_Polymorph", school="Arcane", cost=15000, requiredIds={12824}},
		{id=11416, name="Portal: Ironforge", subText="", level=40, icon="Interface\\Icons\\Spell_Arcane_P ortalIronForge", school="Arcane", cost=13500, faction="Alliance"},
		{id=11417, name="Portal: Orgrimmar", subText="", level=40, icon="Interface\\Icons\\Spell_Arcane_P ortalOrgrimmar", school="Arcane", cost=13500, faction="Horde"},
		{id=10059, name="Portal: Stormwind", subText="", level=40, icon="Interface\\Icons\\Spell_Arcane_P ortalStormWind", school="Arcane", cost=13500, faction="Alliance"},
		{id=11418, name="Portal: Undercity", subText="", level=40, icon="Interface\\Icons\\Spell_Arcane_P ortalUnderCity", school="Arcane", cost=13500, faction="Horde"},
		{id=8446, name="Scorch", subText="Rank 4", level=40, icon="Interface\\Icons\\Spell_Fire_SoulBurn", school="Fire", cost=15000, requiredIds={8445}},
	},
	[42] = {
		{id=10169, name="Amplify Magic", subText="Rank 3", level=42, icon="Interface\\Icons\\Spell_Holy_F lashHeal", school="Arcane", cost=18000, requiredIds={8455}},
		{id=10156, name="Arcane Intellect", subText="Rank 4", level=42, icon="Interface\\Icons\\Spell_Holy_MagicalSentry", school="Arcane", cost=22750, requiredIds={1461}},
		{id=10159, name="Cone of Cold", subText="Rank 3", level=42, icon="Interface\\Icons\\Spell_Frost_Glacier", school="Frost", cost=22750, requiredIds={8492}},
		{id=10144, name="Conjure Food", subText="Rank 5", level=42, icon="Interface\\Icons\\INV_Misc_Food_11", school="Arcane", cost=22750, requiredIds={6129}},
		{id=10148, name="Fireball", subText="Rank 8", level=42, icon="Interface\\Icons\\Spell_Fire_FlameBolt", school="Fire", cost=22750, requiredIds={8402}},
		{id=8462, name="Frost Ward", subText="Rank 3", level=42, icon="Interface\\Icons\\Spell_Frost_FrostWard", school="Frost", cost=18000, requiredIds={8461}},
		{id=12524, name="Pyroblast", subText="Rank 5", level=42, icon="Interface\\Icons\\Spell_Fire_Fireb all02", school="Fire", cost=900, requiredIds={12523}, requiredTalent={name="Pyroblast", tabIndex=2}},
	},
	[44] = {
		{id=13019, name="Blast Wave", subText="Rank 3", level=44, icon="Interface\\Icons\\Spell_Holy_Exco rcism_02", school="Fire", cost=1150, requiredIds={13018}, requiredTalent={name="Blast Wave", tabIndex=2}},
		{id=10185, name="Blizzard", subText="Rank 4", level=44, icon="Interface\\Icons\\Spell_Frost_IceStorm", school="Frost", cost=23000, requiredIds={8427}},
		{id=10179, name="Frostbolt", subText="Rank 8", level=44, icon="Interface\\Icons\\Spell_Frost_FrostBolt02", school="Frost", cost=23000, requiredIds={8408}},
		{id=10191, name="Mana Shield", subText="Rank 4", level=44, icon="Interface\\Icons\\Spell_Shadow_DetectLesserInvisibility", school="Arcane", cost=23000, requiredIds={8495}},
	},
	[46] = {
		{id=10201, name="Arcane Explosion", subText="Rank 5", level=46, icon="Interface\\Icons\\Spell_Nature_WispSplode", school="Arcane", cost=26000, requiredIds={8439}},
		{id=10197, name="Fire Blast", subText="Rank 6", level=46, icon="Interface\\Icons\\Spell_Fire_Fireball", school="Fire", cost=26000, requiredIds={8413}},
		{id=13031, name="Ice Barrier", subText="Rank 2", level=46, icon="Interface\\Icons\\Spell_Ice_Lame nt", school="Frost", cost=6500, requiredIds={11426}, requiredTalent={name="Ice Barrier", tabIndex=3}},
		{id=22782, name="Mage Armor", subText="Rank 2", level=46, icon="Interface\\Icons\\Spell_MageArmor", school="Arcane", cost=28000, requiredIds={6117}},
		{id=10205, name="Scorch", subText="Rank 5", level=46, icon="Interface\\Icons\\Spell_Fire_SoulBurn", school="Fire", cost=26000, requiredIds={8446}},
	},
	[48] = {
		{id=10211, name="Arcane Missiles", subText="Rank 6", level=48, icon="Interface\\Icons\\Spell_Nature_StarFall", school="Arcane", cost=28000, requiredIds={8417}},
		{id=10053, name="Conjure Mana Citrine", subText="", level=48, icon="Interface\\Icons\\INV_Misc_Gem_Opal_01", school="Arcane", cost=28000, requiredIds={3552}},
		{id=10173, name="Dampen Magic", subText="Rank 4", level=48, icon="Interface\\Icons\\Spell_Nature_ AbolishMagic", school="Arcane", cost=28000, requiredIds={8451}},
		{id=10149, name="Fireball", subText="Rank 9", level=48, icon="Interface\\Icons\\Spell_Fire_FlameBolt", school="Fire", cost=28000, requiredIds={10148}},
		{id=10215, name="Flamestrike", subText="Rank 5", level=48, icon="Interface\\Icons\\Spell_Fire_SelfDestruct", school="Fire", cost=28000, requiredIds={8423}},
		{id=12525, name="Pyroblast", subText="Rank 6", level=48, icon="Interface\\Icons\\Spell_Fire_Fireb all02", school="Fire", cost=900, requiredIds={12524}, requiredTalent={name="Pyroblast", tabIndex=2}},
	},
	[50] = {
		{id=10160, name="Cone of Cold", subText="Rank 4", level=50, icon="Interface\\Icons\\Spell_Frost_Glacier", school="Frost", cost=32000, requiredIds={10159}},
		{id=10139, name="Conjure Water", subText="Rank 6", level=50, icon="Interface\\Icons\\INV_Drink_11", school="Arcane", cost=32000, requiredIds={10138}},
		{id=10223, name="Fire Ward", subText="Rank 4", level=50, icon="Interface\\Icons\\Spell_Fire_FireArmor", school="Fire", cost=32000, requiredIds={8458}},
		{id=10180, name="Frostbolt", subText="Rank 9", level=50, icon="Interface\\Icons\\Spell_Frost_FrostBolt02", school="Frost", cost=32000, requiredIds={10179}},
		{id=10219, name="Ice Armor", subText="Rank 3", level=50, icon="Interface\\Icons\\Spell_Frost_FrostArmor02", school="Frost", cost=32000, requiredIds={7320}},
		{id=11419, name="Portal: Darnassus", subText="", level=50, icon="Interface\\Icons\\Spell_Arcane_P ortalDarnassus", school="Arcane", cost=28800, faction="Alliance"},
		{id=11420, name="Portal: Thunder Bluff", subText="", level=50, icon="Interface\\Icons\\Spell_Arca ne_PortalThunderBluff", school="Arcane", cost=28800, faction="Horde"},
	},
	[52] = {
		{id=13020, name="Blast Wave", subText="Rank 4", level=52, icon="Interface\\Icons\\Spell_Holy_Exco rcism_02", school="Fire", cost=1750, requiredIds={13019}, requiredTalent={name="Blast Wave", tabIndex=2}},
		{id=10186, name="Blizzard", subText="Rank 5", level=52, icon="Interface\\Icons\\Spell_Frost_IceStorm", school="Frost", cost=35000, requiredIds={10185}},
		{id=10145, name="Conjure Food", subText="Rank 6", level=52, icon="Interface\\Icons\\INV_Misc_Food_33", school="Arcane", cost=35000, requiredIds={10144}},
		{id=10177, name="Frost Ward", subText="Rank 4", level=52, icon="Interface\\Icons\\Spell_Frost_FrostWard", school="Frost", cost=35000, requiredIds={8462}},
		{id=13032, name="Ice Barrier", subText="Rank 3", level=52, icon="Interface\\Icons\\Spell_Ice_Lame nt", school="Frost", cost=8750, requiredIds={13031}, requiredTalent={name="Ice Barrier", tabIndex=3}},
		{id=10192, name="Mana Shield", subText="Rank 5", level=52, icon="Interface\\Icons\\Spell_Shadow_DetectLesserInvisibility", school="Arcane", cost=35000, requiredIds={10191}},
		{id=10206, name="Scorch", subText="Rank 6", level=52, icon="Interface\\Icons\\Spell_Fire_SoulBurn", school="Fire", cost=35000, requiredIds={10205}},
	},
	[54] = {
		{id=10170, name="Amplify Magic", subText="Rank 4", level=54, icon="Interface\\Icons\\Spell_Holy_F lashHeal", school="Arcane", cost=36000, requiredIds={10169}},
		{id=10202, name="Arcane Explosion", subText="Rank 6", level=54, icon="Interface\\Icons\\Spell_Nature_WispSplode", school="Arcane", cost=36000, requiredIds={10201}},
		{id=10199, name="Fire Blast", subText="Rank 7", level=54, icon="Interface\\Icons\\Spell_Fire_Fireball", school="Fire", cost=36000, requiredIds={10197}},
		{id=10150, name="Fireball", subText="Rank 10", level=54, icon="Interface\\Icons\\Spell_Fire_FlameBolt", school="Fire", cost=36000, requiredIds={10149}},
		{id=10230, name="Frost Nova", subText="Rank 4", level=54, icon="Interface\\Icons\\Spell_Frost_FrostNova", school="Frost", cost=36000, requiredIds={6131}},
		{id=12526, name="Pyroblast", subText="Rank 7", level=54, icon="Interface\\Icons\\Spell_Fire_Fireb all02", school="Fire", cost=1800, requiredIds={12525}, requiredTalent={name="Pyroblast", tabIndex=2}},
	},
	[56] = {
		{id=10157, name="Arcane Intellect", subText="Rank 5", level=56, icon="Interface\\Icons\\Spell_Holy_MagicalSentry", school="Arcane", cost=38000, requiredIds={10156}},
		{id=10212, name="Arcane Missiles", subText="Rank 7", level=56, icon="Interface\\Icons\\Spell_Nature_StarFall", school="Arcane", cost=38000, requiredIds={10211}},
		{id=10216, name="Flamestrike", subText="Rank 6", level=56, icon="Interface\\Icons\\Spell_Fire_SelfDestruct", school="Fire", cost=38000, requiredIds={10215}},
		{id=10181, name="Frostbolt", subText="Rank 10", level=56, icon="Interface\\Icons\\Spell_Frost_FrostBolt02", school="Frost", cost=38000, requiredIds={10180}},
	},
	[58] = {
		{id=10161, name="Cone of Cold", subText="Rank 5", level=58, icon="Interface\\Icons\\Spell_Frost_Glacier", school="Frost", cost=40000, requiredIds={10160}},
		{id=10054, name="Conjure Mana Ruby", subText="", level=58, icon="Interface\\Icons\\INV_Misc_Gem_Ruby_01", school="Arcane", cost=40000, requiredIds={10053}},
		{id=13033, name="Ice Barrier", subText="Rank 4", level=58, icon="Interface\\Icons\\Spell_Ice_Lame nt", school="Frost", cost=9000, requiredIds={13032}, requiredTalent={name="Ice Barrier", tabIndex=3}},
		{id=22783, name="Mage Armor", subText="Rank 3", level=58, icon="Interface\\Icons\\Spell_MageArmor", school="Arcane", cost=40000, requiredIds={22782}},
		{id=10207, name="Scorch", subText="Rank 7", level=58, icon="Interface\\Icons\\Spell_Fire_SoulBurn", school="Fire", cost=40000, requiredIds={10206}},
	},
	[60] = {
		{id=13021, name="Blast Wave", subText="Rank 5", level=60, icon="Interface\\Icons\\Spell_Holy_Exco rcism_02", school="Fire", cost=2100, requiredIds={13020}, requiredTalent={name="Blast Wave", tabIndex=2}},
		{id=10187, name="Blizzard", subText="Rank 6", level=60, icon="Interface\\Icons\\Spell_Frost_IceStorm", school="Frost", cost=42000, requiredIds={10186}},
		{id=10174, name="Dampen Magic", subText="Rank 5", level=60, icon="Interface\\Icons\\Spell_Nature_ AbolishMagic", school="Arcane", cost=42000, requiredIds={10173}},
		{id=10225, name="Fire Ward", subText="Rank 5", level=60, icon="Interface\\Icons\\Spell_Fire_FireArmor", school="Fire", cost=42000, requiredIds={10223}},
		{id=10151, name="Fireball", subText="Rank 11", level=60, icon="Interface\\Icons\\Spell_Fire_FlameBolt", school="Fire", cost=42000, requiredIds={10150}},
		{id=10220, name="Ice Armor", subText="Rank 4", level=60, icon="Interface\\Icons\\Spell_Frost_FrostArmor02", school="Frost", cost=42000, requiredIds={10219}},
		{id=10193, name="Mana Shield", subText="Rank 6", level=60, icon="Interface\\Icons\\Spell_Shadow_DetectLesserInvisibility", school="Arcane", cost=42000, requiredIds={10192}},
		{id=12826, name="Polymorph", subText="Rank 4", level=60, icon="Interface\\Icons\\Spell_Nature_Polymorph", school="Arcane", cost=42000, requiredIds={12825}},
		{id=18809, name="Pyroblast", subText="Rank 8", level=60, icon="Interface\\Icons\\Spell_Fire_Fireb all02", school="Fire", cost=1890, requiredIds={12526}, requiredTalent={name="Pyroblast", tabIndex=2}},
	},
}
