setfenv(1, WhatsTraining)

OverridenSpells["PRIEST"] = {
}

ClassSpellsByLevel["PRIEST"] = {
	[1] = {
		{id=1243, name="Power Word: Fortitude", subText="Rank 1", level=1, icon="Interface\\Icons\\Spell_Holy_WordFortitude", school="Discipline", cost=10},
	},
	[4] = {
		{id=2052, name="Lesser Heal", subText="Rank 2", level=4, icon="Interface\\Icons\\Spell_Holy_LesserHeal", school="Holy", cost=100, requiredIds={2050}},
		{id=589, name="Shadow Word: Pain", subText="Rank 1", level=4, icon="Interface\\Icons\\Spell_Shadow_ShadowWordPain", school="Shadow Magic", cost=100},
	},
	[6] = {
		{id=17, name="Power Word: Shield", subText="Rank 1", level=6, icon="Interface\\Icons\\Spell_Holy_PowerWordShield", school="Discipline", cost=100},
		{id=591, name="Smite", subText="Rank 2", level=6, icon="Interface\\Icons\\Spell_Holy_HolySmite", school="Holy", cost=100, requiredIds={585}},
	},
	[8] = {
		{id=586, name="Fade", subText="Rank 1", level=8, icon="Interface\\Icons\\Spell_Magic_LesserInvisibilty", school="Shadow Magic", cost=200},
		{id=139, name="Renew", subText="Rank 1", level=8, icon="Interface\\Icons\\Spell_Holy_Renew", school="Holy", cost=200},
	},
	[10] = {
		{id=2053, name="Lesser Heal", subText="Rank 3", level=10, icon="Interface\\Icons\\Spell_Holy_LesserHeal", school="Holy", cost=300, requiredIds={2052}},
		{id=8092, name="Mind Blast", subText="Rank 1", level=10, icon="Interface\\Icons\\Spell_Shadow_UnholyFrenzy", school="Shadow Magic", cost=300},
		{id=2006, name="Resurrection", subText="Rank 1", level=10, icon="Interface\\Icons\\Spell_Holy_Resurrection", school="Holy", cost=300},
		{id=594, name="Shadow Word: Pain", subText="Rank 2", level=10, icon="Interface\\Icons\\Spell_Shadow_ShadowWordPain", school="Shadow Magic", cost=300, requiredIds={589}},
	},
	[12] = {
		{id=588, name="Inner Fire", subText="Rank 1", level=12, icon="Interface\\Icons\\Spell_Holy_InnerFire", school="Discipline", cost=800},
		{id=1244, name="Power Word: Fortitude", subText="Rank 2", level=12, icon="Interface\\Icons\\Spell_Holy_WordFortitude", school="Discipline", cost=800, requiredIds={1243}},
		{id=592, name="Power Word: Shield", subText="Rank 2", level=12, icon="Interface\\Icons\\Spell_Holy_PowerWordShield", school="Discipline", cost=800, requiredIds={17}},
	},
	[14] = {
		{id=528, name="Cure Disease", subText="", level=14, icon="Interface\\Icons\\Spell_Holy_NullifyDisease", school="Holy", cost=1200},
		{id=8122, name="Psychic Scream", subText="Rank 1", level=14, icon="Interface\\Icons\\Spell_Shadow_PsychicScream", school="Shadow Magic", cost=1200},
		{id=6074, name="Renew", subText="Rank 2", level=14, icon="Interface\\Icons\\Spell_Holy_Renew", school="Holy", cost=1200, requiredIds={139}},
		{id=598, name="Smite", subText="Rank 3", level=14, icon="Interface\\Icons\\Spell_Holy_HolySmite", school="Holy", cost=1200, requiredIds={591}},
	},
	[16] = {
		{id=2054, name="Heal", subText="Rank 1", level=16, icon="Interface\\Icons\\Spell_Holy_Heal", school="Holy", cost=1600},
		{id=8102, name="Mind Blast", subText="Rank 2", level=16, icon="Interface\\Icons\\Spell_Shadow_UnholyFrenzy", school="Shadow Magic", cost=1600, requiredIds={8092}},
	},
	[18] = {
		{id=19236, name="Desperate Prayer", subText="Rank 2", level=18, icon="Interface\\Icons\\Spell_H oly_Restoration", school="Holy", cost=100},
		{id=527, name="Dispel Magic", subText="Rank 1", level=18, icon="Interface\\Icons\\Spell_Holy_DispelMagic", school="Discipline", cost=2000},
		{id=600, name="Power Word: Shield", subText="Rank 3", level=18, icon="Interface\\Icons\\Spell_Holy_PowerWordShield", school="Discipline", cost=2000, requiredIds={592}},
		{id=970, name="Shadow Word: Pain", subText="Rank 3", level=18, icon="Interface\\Icons\\Spell_Shadow_ShadowWordPain", school="Shadow Magic", cost=2000, requiredIds={594}},
		{id=19296, name="Starshards", subText="Rank 2", level=18, icon="Interface\\Icons\\Spell_Arcane_ StarFire", school="Discipline", cost=100},
	},
	[20] = {
		{id=9578, name="Fade", subText="Rank 2", level=20, icon="Interface\\Icons\\Spell_Magic_LesserInvisibilty", school="Shadow Magic", cost=3000, requiredIds={586}},
		{id=2061, name="Flash Heal", subText="Rank 1", level=20, icon="Interface\\Icons\\Spell_Holy_FlashHeal", school="Holy", cost=3000},
		{id=19281, name="Hex of Weakness", subText="Rank 2", level=20, icon="Interface\\Icons\\Spell_Sh adow_FingerOfDeath", school="Shadow", cost=150},
		{id=14914, name="Holy Fire", subText="Rank 1", level=20, icon="Interface\\Icons\\Spell_Holy_SearingLight", school="Holy", cost=3000},
		{id=7128, name="Inner Fire", subText="Rank 2", level=20, icon="Interface\\Icons\\Spell_Holy_InnerFire", school="Discipline", cost=3000, requiredIds={588}},
		{id=453, name="Mind Soothe", subText="Rank 1", level=20, icon="Interface\\Icons\\Spell_Holy_MindSooth", school="Shadow Magic", cost=3000},
		{id=6075, name="Renew", subText="Rank 3", level=20, icon="Interface\\Icons\\Spell_Holy_Renew", school="Holy", cost=3000, requiredIds={6074}},
		{id=9484, name="Shackle Undead", subText="Rank 1", level=20, icon="Interface\\Icons\\Spell_Nature_Slow", school="Discipline", cost=3000},
		{id=19261, name="Touch of Weakness", subText="Rank 2", level=20, icon="Interface\\Icons\\Spell_ Shadow_DeadofNight", school="Shadow", cost=200},
	},
	[22] = {
		{id=2055, name="Heal", subText="Rank 2", level=22, icon="Interface\\Icons\\Spell_Holy_Heal", school="Holy", cost=4000, requiredIds={2054}},
		{id=8103, name="Mind Blast", subText="Rank 3", level=22, icon="Interface\\Icons\\Spell_Shadow_UnholyFrenzy", school="Shadow Magic", cost=4000, requiredIds={8102}},
		{id=2096, name="Mind Vision", subText="Rank 1", level=22, icon="Interface\\Icons\\Spell_Holy_MindVision", school="Shadow Magic", cost=4000},
		{id=2010, name="Resurrection", subText="Rank 2", level=22, icon="Interface\\Icons\\Spell_Holy_Resurrection", school="Holy", cost=4000, requiredIds={2006}},
		{id=984, name="Smite", subText="Rank 4", level=22, icon="Interface\\Icons\\Spell_Holy_HolySmite", school="Holy", cost=4000, requiredIds={598}},
	},
	[24] = {
		{id=15262, name="Holy Fire", subText="Rank 2", level=24, icon="Interface\\Icons\\Spell_Holy_SearingLight", school="Holy", cost=5000, requiredIds={14914}},
		{id=8129, name="Mana Burn", subText="Rank 1", level=24, icon="Interface\\Icons\\Spell_Shadow_ManaBurn", school="Shadow Magic", cost=5000},
		{id=1245, name="Power Word: Fortitude", subText="Rank 3", level=24, icon="Interface\\Icons\\Spell_Holy_WordFortitude", school="Discipline", cost=5000, requiredIds={1244}},
		{id=3747, name="Power Word: Shield", subText="Rank 4", level=24, icon="Interface\\Icons\\Spell_Holy_PowerWordShield", school="Discipline", cost=5000, requiredIds={600}},
	},
	[26] = {
		{id=19238, name="Desperate Prayer", subText="Rank 3", level=26, icon="Interface\\Icons\\Spell_H oly_Restoration", school="Holy", cost=300},
		{id=9472, name="Flash Heal", subText="Rank 2", level=26, icon="Interface\\Icons\\Spell_Holy_FlashHeal", school="Holy", cost=6000, requiredIds={2061}},
		{id=6076, name="Renew", subText="Rank 4", level=26, icon="Interface\\Icons\\Spell_Holy_Renew", school="Holy", cost=6000, requiredIds={6075}},
		{id=992, name="Shadow Word: Pain", subText="Rank 4", level=26, icon="Interface\\Icons\\Spell_Shadow_ShadowWordPain", school="Shadow Magic", cost=6000, requiredIds={970}},
		{id=19299, name="Starshards", subText="Rank 3", level=26, icon="Interface\\Icons\\Spell_Arcane_ StarFire", school="Discipline", cost=300, requiredIds={19296}},
	},
	[28] = {
		{id=19276, name="Devouring Plague", subText="Rank 2", level=28, icon="Interface\\Icons\\Spell_S hadow_BlackPlague", school="Shadow", cost=400},
		{id=6063, name="Heal", subText="Rank 3", level=28, icon="Interface\\Icons\\Spell_Holy_Heal02", school="Holy", cost=8000, requiredIds={2055}},
		{id=15430, name="Holy Nova", subText="Rank 2", level=28, icon="Interface\\Icons\\Spell_Holy_Hol yNova", school="Holy", cost=400, requiredTalent={name="Talent 15237", tabIndex=1}},
		{id=8104, name="Mind Blast", subText="Rank 4", level=28, icon="Interface\\Icons\\Spell_Shadow_UnholyFrenzy", school="Shadow Magic", cost=8000, requiredIds={8103}},
		{id=17311, name="Mind Flay", subText="Rank 2", level=28, icon="Interface\\Icons\\Spell_Shadow_S iphonMana", school="Shadow", cost=400, requiredTalent={name="Talent 15407", tabIndex=1}},
		{id=8124, name="Psychic Scream", subText="Rank 2", level=28, icon="Interface\\Icons\\Spell_Shadow_PsychicScream", school="Shadow Magic", cost=8000, requiredIds={8122}},
		{id=19308, name="Shadowguard", subText="Rank 2", level=28, icon="Interface\\Icons\\Spell_Nature _LightningShield", school="Shadow", cost=400},
	},
	[30] = {
		{id=19289, name="Elune's Grace", subText="Rank 2", level=30, icon="Interface\\Icons\\Spell _Holy_ElunesGrace", school="Discipline", cost=500},
		{id=9579, name="Fade", subText="Rank 3", level=30, icon="Interface\\Icons\\Spell_Magic_LesserInvisibilty", school="Shadow Magic", cost=10000, requiredIds={9578}},
		{id=19271, name="Feedback", subText="Rank 2", level=30, icon="Interface\\Icons\\Spell_Shadow_Ri tualOfSacrifice", school="Discipline", cost=450},
		{id=19282, name="Hex of Weakness", subText="Rank 3", level=30, icon="Interface\\Icons\\Spell_Sh adow_FingerOfDeath", school="Shadow", cost=500},
		{id=15263, name="Holy Fire", subText="Rank 3", level=30, icon="Interface\\Icons\\Spell_Holy_SearingLight", school="Holy", cost=10000, requiredIds={15262}},
		{id=602, name="Inner Fire", subText="Rank 3", level=30, icon="Interface\\Icons\\Spell_Holy_InnerFire", school="Discipline", cost=10000, requiredIds={7128}},
		{id=605, name="Mind Control", subText="Rank 1", level=30, icon="Interface\\Icons\\Spell_Shadow_ShadowWordDominate", school="Shadow Magic", cost=10000},
		{id=6065, name="Power Word: Shield", subText="Rank 5", level=30, icon="Interface\\Icons\\Spell_Holy_PowerWordShield", school="Discipline", cost=10000, requiredIds={3747}},
		{id=596, name="Prayer of Healing", subText="Rank 1", level=30, icon="Interface\\Icons\\Spell_Holy_PrayerOfHealing02", school="Holy", cost=10000},
		{id=976, name="Shadow Protection", subText="Rank 1", level=30, icon="Interface\\Icons\\Spell_Shadow_AntiShadow", school="Shadow Magic", cost=10000},
		{id=1004, name="Smite", subText="Rank 5", level=30, icon="Interface\\Icons\\Spell_Holy_HolySmite", school="Holy", cost=10000, requiredIds={984}},
		{id=19262, name="Touch of Weakness", subText="Rank 3", level=30, icon="Interface\\Icons\\Spell_ Shadow_DeadofNight", school="Shadow", cost=500},
	},
	[32] = {
		{id=552, name="Abolish Disease", subText="", level=32, icon="Interface\\Icons\\Spell_Nature_NullifyDisease", school="Holy", cost=11000},
		{id=9473, name="Flash Heal", subText="Rank 3", level=32, icon="Interface\\Icons\\Spell_Holy_FlashHeal", school="Holy", cost=11000, requiredIds={9472}},
		{id=8131, name="Mana Burn", subText="Rank 2", level=32, icon="Interface\\Icons\\Spell_Shadow_ManaBurn", school="Shadow Magic", cost=11000, requiredIds={8129}},
		{id=6077, name="Renew", subText="Rank 5", level=32, icon="Interface\\Icons\\Spell_Holy_Renew", school="Holy", cost=11000, requiredIds={6076}},
	},
	[34] = {
		{id=19240, name="Desperate Prayer", subText="Rank 4", level=34, icon="Interface\\Icons\\Spell_H oly_Restoration", school="Holy", cost=600},
		{id=6064, name="Heal", subText="Rank 4", level=34, icon="Interface\\Icons\\Spell_Holy_Heal02", school="Holy", cost=12000, requiredIds={6063}},
		{id=1706, name="Levitate", subText="", level=34, icon="Interface\\Icons\\Spell_Holy_LayOnHands", school="Discipline", cost=12000},
		{id=8105, name="Mind Blast", subText="Rank 5", level=34, icon="Interface\\Icons\\Spell_Shadow_UnholyFrenzy", school="Shadow Magic", cost=12000, requiredIds={8104}},
		{id=10880, name="Resurrection", subText="Rank 3", level=34, icon="Interface\\Icons\\Spell_Holy_Resurrection", school="Holy", cost=12000, requiredIds={2010}},
		{id=2767, name="Shadow Word: Pain", subText="Rank 5", level=34, icon="Interface\\Icons\\Spell_Shadow_ShadowWordPain", school="Shadow Magic", cost=12000, requiredIds={992}},
		{id=19302, name="Starshards", subText="Rank 4", level=34, icon="Interface\\Icons\\Spell_Arcane_ StarFire", school="Discipline", cost=600, requiredIds={19299}},
	},
	[36] = {
		{id=19277, name="Devouring Plague", subText="Rank 3", level=36, icon="Interface\\Icons\\Spell_S hadow_BlackPlague", school="Shadow", cost=700},
		{id=988, name="Dispel Magic", subText="Rank 2", level=36, icon="Interface\\Icons\\Spell_Holy_DispelMagic", school="Discipline", cost=14000, requiredIds={527}},
		{id=15264, name="Holy Fire", subText="Rank 4", level=36, icon="Interface\\Icons\\Spell_Holy_SearingLight", school="Holy", cost=14000, requiredIds={15263}},
		{id=15431, name="Holy Nova", subText="Rank 3", level=36, icon="Interface\\Icons\\Spell_Holy_Hol yNova", school="Holy", cost=700, requiredIds={15430}, requiredTalent={name="Talent 15237", tabIndex=1}},
		{id=17312, name="Mind Flay", subText="Rank 3", level=36, icon="Interface\\Icons\\Spell_Shadow_S iphonMana", school="Shadow", cost=700, requiredIds={17311}, requiredTalent={name="Talent 15407", tabIndex=1}},
		{id=8192, name="Mind Soothe", subText="Rank 2", level=36, icon="Interface\\Icons\\Spell_Holy_MindSooth", school="Shadow Magic", cost=14000, requiredIds={453}},
		{id=2791, name="Power Word: Fortitude", subText="Rank 4", level=36, icon="Interface\\Icons\\Spell_Holy_WordFortitude", school="Discipline", cost=14000, requiredIds={1245}},
		{id=6066, name="Power Word: Shield", subText="Rank 6", level=36, icon="Interface\\Icons\\Spell_Holy_PowerWordShield", school="Discipline", cost=14000, requiredIds={6065}},
		{id=19309, name="Shadowguard", subText="Rank 3", level=36, icon="Interface\\Icons\\Spell_Nature _LightningShield", school="Shadow", cost=700},
	},
	[38] = {
		{id=9474, name="Flash Heal", subText="Rank 4", level=38, icon="Interface\\Icons\\Spell_Holy_FlashHeal", school="Holy", cost=16000, requiredIds={9473}},
		{id=6078, name="Renew", subText="Rank 6", level=38, icon="Interface\\Icons\\Spell_Holy_Renew", school="Holy", cost=16000, requiredIds={6077}},
		{id=6060, name="Smite", subText="Rank 6", level=38, icon="Interface\\Icons\\Spell_Holy_HolySmite", school="Holy", cost=16000, requiredIds={1004}},
	},
	[40] = {
		{id=14818, name="Divine Spirit", subText="Rank 2", level=40, icon="Interface\\Icons\\Spell_Holy_DivineSpirit", school="Discipline", cost=900, requiredTalent={name="Talent 14752", tabIndex=1}},
		{id=19291, name="Elune's Grace", subText="Rank 3", level=40, icon="Interface\\Icons\\Spell _Holy_ElunesGrace", school="Discipline", cost=900, requiredIds={19289}},
		{id=9592, name="Fade", subText="Rank 4", level=40, icon="Interface\\Icons\\Spell_Magic_LesserInvisibilty", school="Shadow Magic", cost=18000, requiredIds={9579}},
		{id=19273, name="Feedback", subText="Rank 3", level=40, icon="Interface\\Icons\\Spell_Shadow_Ri tualOfSacrifice", school="Discipline", cost=810},
		{id=2060, name="Greater Heal", subText="Rank 1", level=40, icon="Interface\\Icons\\Spell_Holy_GreaterHeal", school="Holy", cost=18000},
		{id=19283, name="Hex of Weakness", subText="Rank 4", level=40, icon="Interface\\Icons\\Spell_Sh adow_FingerOfDeath", school="Shadow", cost=900},
		{id=1006, name="Inner Fire", subText="Rank 4", level=40, icon="Interface\\Icons\\Spell_Holy_InnerFire", school="Discipline", cost=18000, requiredIds={602}},
		{id=10874, name="Mana Burn", subText="Rank 3", level=40, icon="Interface\\Icons\\Spell_Shadow_ManaBurn", school="Shadow Magic", cost=18000, requiredIds={8131}},
		{id=8106, name="Mind Blast", subText="Rank 6", level=40, icon="Interface\\Icons\\Spell_Shadow_UnholyFrenzy", school="Shadow Magic", cost=18000, requiredIds={8105}},
		{id=996, name="Prayer of Healing", subText="Rank 2", level=40, icon="Interface\\Icons\\Spell_Holy_PrayerOfHealing02", school="Holy", cost=18000, requiredIds={596}},
		{id=9485, name="Shackle Undead", subText="Rank 2", level=40, icon="Interface\\Icons\\Spell_Nature_Slow", school="Discipline", cost=18000, requiredIds={9484}},
		{id=19264, name="Touch of Weakness", subText="Rank 4", level=40, icon="Interface\\Icons\\Spell_Shadow_DeadofNight", school="Shadow", cost=900},
	},
	[42] = {
		{id=19241, name="Desperate Prayer", subText="Rank 5", level=42, icon="Interface\\Icons\\Spell_H oly_Restoration", school="Holy", cost=1100},
		{id=15265, name="Holy Fire", subText="Rank 5", level=42, icon="Interface\\Icons\\Spell_Holy_SearingLight", school="Holy", cost=22000, requiredIds={15264}},
		{id=10898, name="Power Word: Shield", subText="Rank 7", level=42, icon="Interface\\Icons\\Spell_Holy_PowerWordShield", school="Discipline", cost=22000, requiredIds={6066}},
		{id=10888, name="Psychic Scream", subText="Rank 3", level=42, icon="Interface\\Icons\\Spell_Shadow_PsychicScream", school="Shadow Magic", cost=22000, requiredIds={8124}},
		{id=10957, name="Shadow Protection", subText="Rank 2", level=42, icon="Interface\\Icons\\Spell_Shadow_AntiShadow", school="Shadow Magic", cost=22000, requiredIds={976}},
		{id=10892, name="Shadow Word: Pain", subText="Rank 6", level=42, icon="Interface\\Icons\\Spell_Shadow_ShadowWordPain", school="Shadow Magic", cost=22000, requiredIds={2767}},
		{id=19303, name="Starshards", subText="Rank 5", level=42, icon="Interface\\Icons\\Spell_Arcane_ StarFire", school="Discipline", cost=1100, requiredIds={19302}},
	},
	[44] = {
		{id=19278, name="Devouring Plague", subText="Rank 4", level=44, icon="Interface\\Icons\\Spell_S hadow_BlackPlague", school="Shadow", cost=1200},
		{id=10915, name="Flash Heal", subText="Rank 5", level=44, icon="Interface\\Icons\\Spell_Holy_FlashHeal", school="Holy", cost=24000, requiredIds={9474}},
		{id=27799, name="Holy Nova", subText="Rank 4", level=44, icon="Interface\\Icons\\Spell_Holy_Hol yNova", school="Holy", cost=1200, requiredIds={15431}, requiredTalent={name="Talent 15237", tabIndex=1}},
		{id=10911, name="Mind Control", subText="Rank 2", level=44, icon="Interface\\Icons\\Spell_Shadow_ShadowWordDominate", school="Shadow Magic", cost=24000, requiredIds={605}},
		{id=17313, name="Mind Flay", subText="Rank 4", level=44, icon="Interface\\Icons\\Spell_Shadow_S iphonMana", school="Shadow", cost=1200, requiredIds={17312}, requiredTalent={name="Talent 15407", tabIndex=1}},
		{id=10909, name="Mind Vision", subText="Rank 2", level=44, icon="Interface\\Icons\\Spell_Holy_MindVision", school="Shadow Magic", cost=24000, requiredIds={2096}},
		{id=10927, name="Renew", subText="Rank 7", level=44, icon="Interface\\Icons\\Spell_Holy_Renew", school="Holy", cost=24000, requiredIds={6078}},
		{id=19310, name="Shadowguard", subText="Rank 4", level=44, icon="Interface\\Icons\\Spell_Nature _LightningShield", school="Shadow", cost=1000},
	},
	[46] = {
		{id=10963, name="Greater Heal", subText="Rank 2", level=46, icon="Interface\\Icons\\Spell_Holy_GreaterHeal", school="Holy", cost=26000, requiredIds={2060}},
		{id=10945, name="Mind Blast", subText="Rank 7", level=46, icon="Interface\\Icons\\Spell_Shadow_UnholyFrenzy", school="Shadow Magic", cost=26000, requiredIds={8106}},
		{id=10881, name="Resurrection", subText="Rank 4", level=46, icon="Interface\\Icons\\Spell_Holy_Resurrection", school="Holy", cost=26000, requiredIds={10880}},
		{id=10933, name="Smite", subText="Rank 7", level=46, icon="Interface\\Icons\\Spell_Holy_HolySmite", school="Holy", cost=26000, requiredIds={6060}},
	},
	[48] = {
		{id=15266, name="Holy Fire", subText="Rank 6", level=48, icon="Interface\\Icons\\Spell_Holy_SearingLight", school="Holy", cost=28000, requiredIds={15265}},
		{id=10875, name="Mana Burn", subText="Rank 4", level=48, icon="Interface\\Icons\\Spell_Shadow_ManaBurn", school="Shadow Magic", cost=28000, requiredIds={10874}},
		{id=10937, name="Power Word: Fortitude", subText="Rank 5", level=48, icon="Interface\\Icons\\Spell_Holy_WordFortitude", school="Discipline", cost=28000, requiredIds={2791}},
		{id=10899, name="Power Word: Shield", subText="Rank 8", level=48, icon="Interface\\Icons\\Spell_Holy_PowerWordShield", school="Discipline", cost=28000, requiredIds={10898}},
	},
	[50] = {
		{id=19242, name="Desperate Prayer", subText="Rank 6", level=50, icon="Interface\\Icons\\Spell_H oly_Restoration", school="Holy", cost=1500},
		{id=14819, name="Divine Spirit", subText="Rank 3", level=50, icon="Interface\\Icons\\Spell_Holy_DivineSpirit", school="Discipline", cost=1500, requiredIds={14818}, requiredTalent={name="Talent 14752", tabIndex=1}},
		{id=19292, name="Elune's Grace", subText="Rank 4", level=50, icon="Interface\\Icons\\Spell _Holy_ElunesGrace", school="Discipline", cost=1500, requiredIds={19291}},
		{id=10941, name="Fade", subText="Rank 5", level=50, icon="Interface\\Icons\\Spell_Magic_LesserInvisibilty", school="Shadow Magic", cost=30000, requiredIds={9592}},
		{id=10916, name="Flash Heal", subText="Rank 6", level=50, icon="Interface\\Icons\\Spell_Holy_FlashHeal", school="Holy", cost=30000, requiredIds={10915}},
		{id=19284, name="Hex of Weakness", subText="Rank 5", level=50, icon="Interface\\Icons\\Spell_Sh adow_FingerOfDeath", school="Shadow", cost=1500},
		{id=10951, name="Inner Fire", subText="Rank 5", level=50, icon="Interface\\Icons\\Spell_Holy_InnerFire", school="Discipline", cost=30000, requiredIds={1006}},
		{id=27870, name="Lightwell", subText="Rank 2", level=50, icon="Interface\\Icons\\Spell_Holy_SummonLightwell", school="Holy", cost=1200, requiredTalent={name="Talent 724", tabIndex=1}},
		{id=10960, name="Prayer of Healing", subText="Rank 3", level=50, icon="Interface\\Icons\\Spell_Holy_PrayerOfHealing02", school="Holy", cost=30000, requiredIds={996}},
		{id=10928, name="Renew", subText="Rank 8", level=50, icon="Interface\\Icons\\Spell_Holy_Renew", school="Holy", cost=30000, requiredIds={10927}},
		{id=10893, name="Shadow Word: Pain", subText="Rank 7", level=50, icon="Interface\\Icons\\Spell_Shadow_ShadowWordPain", school="Shadow Magic", cost=30000, requiredIds={10892}},
		{id=19304, name="Starshards", subText="Rank 6", level=50, icon="Interface\\Icons\\Spell_Arcane_ StarFire", school="Discipline", cost=1500, requiredIds={19303}},
		{id=19265, name="Touch of Weakness", subText="Rank 5", level=50, icon="Interface\\Icons\\Spell_Shadow_DeadofNight", school="Shadow", cost=1500},
	},
	[52] = {
		{id=19279, name="Devouring Plague", subText="Rank 5", level=52, icon="Interface\\Icons\\Spell_S hadow_BlackPlague", school="Shadow", cost=1900},
		{id=10964, name="Greater Heal", subText="Rank 3", level=52, icon="Interface\\Icons\\Spell_Holy_GreaterHeal", school="Holy", cost=38000, requiredIds={10963}},
		{id=27800, name="Holy Nova", subText="Rank 5", level=52, icon="Interface\\Icons\\Spell_Holy_Hol yNova", school="Holy", cost=1900, requiredIds={27799}, requiredTalent={name="Talent 15237", tabIndex=1}},
		{id=10946, name="Mind Blast", subText="Rank 8", level=52, icon="Interface\\Icons\\Spell_Shadow_UnholyFrenzy", school="Shadow Magic", cost=38000, requiredIds={10945}},
		{id=17314, name="Mind Flay", subText="Rank 5", level=52, icon="Interface\\Icons\\Spell_Shadow_S iphonMana", school="Shadow", cost=1900, requiredIds={17313}, requiredTalent={name="Talent 15407", tabIndex=1}},
		{id=10953, name="Mind Soothe", subText="Rank 3", level=52, icon="Interface\\Icons\\Spell_Holy_MindSooth", school="Shadow Magic", cost=38000, requiredIds={8192}},
		{id=19311, name="Shadowguard", subText="Rank 5", level=52, icon="Interface\\Icons\\Spell_Nature _LightningShield", school="Shadow", cost=1200},
	},
	[54] = {
		{id=15267, name="Holy Fire", subText="Rank 7", level=54, icon="Interface\\Icons\\Spell_Holy_SearingLight", school="Holy", cost=40000, requiredIds={15266}},
		{id=10900, name="Power Word: Shield", subText="Rank 9", level=54, icon="Interface\\Icons\\Spell_Holy_PowerWordShield", school="Discipline", cost=40000, requiredIds={10899}},
		{id=10934, name="Smite", subText="Rank 8", level=54, icon="Interface\\Icons\\Spell_Holy_HolySmite", school="Holy", cost=40000, requiredIds={10933}},
	},
	[56] = {
		{id=10917, name="Flash Heal", subText="Rank 7", level=56, icon="Interface\\Icons\\Spell_Holy_FlashHeal", school="Holy", cost=42000, requiredIds={10916}},
		{id=10876, name="Mana Burn", subText="Rank 5", level=56, icon="Interface\\Icons\\Spell_Shadow_ManaBurn", school="Shadow Magic", cost=42000, requiredIds={10875}},
		{id=10890, name="Psychic Scream", subText="Rank 4", level=56, icon="Interface\\Icons\\Spell_Shadow_PsychicScream", school="Shadow Magic", cost=42000, requiredIds={10888}},
		{id=10929, name="Renew", subText="Rank 9", level=56, icon="Interface\\Icons\\Spell_Holy_Renew", school="Holy", cost=42000, requiredIds={10928}},
		{id=10958, name="Shadow Protection", subText="Rank 3", level=56, icon="Interface\\Icons\\Spell_Shadow_AntiShadow", school="Shadow Magic", cost=42000, requiredIds={10957}},
	},
	[58] = {
		{id=19243, name="Desperate Prayer", subText="Rank 7", level=58, icon="Interface\\Icons\\Spell_H oly_Restoration", school="Holy", cost=2200},
		{id=10965, name="Greater Heal", subText="Rank 4", level=58, icon="Interface\\Icons\\Spell_Holy_GreaterHeal", school="Holy", cost=44000, requiredIds={10964}},
		{id=10947, name="Mind Blast", subText="Rank 9", level=58, icon="Interface\\Icons\\Spell_Shadow_UnholyFrenzy", school="Shadow Magic", cost=44000, requiredIds={10946}},
		{id=10912, name="Mind Control", subText="Rank 3", level=58, icon="Interface\\Icons\\Spell_Shadow_ShadowWordDominate", school="Shadow Magic", cost=44000, requiredIds={10911}},
		{id=20770, name="Resurrection", subText="Rank 5", level=58, icon="Interface\\Icons\\Spell_Holy_Resurrection", school="Holy", cost=44000, requiredIds={10881}},
		{id=10894, name="Shadow Word: Pain", subText="Rank 8", level=58, icon="Interface\\Icons\\Spell_Shadow_ShadowWordPain", school="Shadow Magic", cost=44000, requiredIds={10893}},
		{id=19305, name="Starshards", subText="Rank 7", level=58, icon="Interface\\Icons\\Spell_Arcane_ StarFire", school="Discipline", cost=2200, requiredIds={19304}},
	},
	[60] = {
		{id=19280, name="Devouring Plague", subText="Rank 6", level=60, icon="Interface\\Icons\\Spell_S hadow_BlackPlague", school="Shadow", cost=2300},
		{id=27841, name="Divine Spirit", subText="Rank 4", level=60, icon="Interface\\Icons\\Spell_Holy_DivineSpirit", school="Discipline", cost=2300, requiredIds={14819}, requiredTalent={name="Talent 14752", tabIndex=1}},
		{id=19293, name="Elune's Grace", subText="Rank 5", level=60, icon="Interface\\Icons\\Spell _Holy_ElunesGrace", school="Discipline", cost=2070, requiredIds={19292}},
		{id=10942, name="Fade", subText="Rank 6", level=60, icon="Interface\\Icons\\Spell_Magic_LesserInvisibilty", school="Shadow Magic", cost=46000, requiredIds={10941}},
		{id=19285, name="Hex of Weakness", subText="Rank 6", level=60, icon="Interface\\Icons\\Spell_Sh adow_FingerOfDeath", school="Shadow", cost=2300},
		{id=15261, name="Holy Fire", subText="Rank 8", level=60, icon="Interface\\Icons\\Spell_Holy_SearingLight", school="Holy", cost=46000, requiredIds={15267}},
		{id=27801, name="Holy Nova", subText="Rank 6", level=60, icon="Interface\\Icons\\Spell_Holy_Hol yNova", school="Holy", cost=2300, requiredIds={27800}, requiredTalent={name="Talent 15237", tabIndex=1}},
		{id=10952, name="Inner Fire", subText="Rank 6", level=60, icon="Interface\\Icons\\Spell_Holy_InnerFire", school="Discipline", cost=46000, requiredIds={10951}},
		{id=27871, name="Lightwell", subText="Rank 3", level=60, icon="Interface\\Icons\\Spell_Holy_SummonLightwell", school="Holy", cost=1500, requiredIds={27870}, requiredTalent={name="Talent 724", tabIndex=1}},
		{id=18807, name="Mind Flay", subText="Rank 6", level=60, icon="Interface\\Icons\\Spell_Shadow_S iphonMana", school="Shadow", cost=2300, requiredIds={17314}, requiredTalent={name="Talent 15407", tabIndex=1}},
		{id=10938, name="Power Word: Fortitude", subText="Rank 6", level=60, icon="Interface\\Icons\\Spell_Holy_WordFortitude", school="Discipline", cost=46000, requiredIds={10937}},
		{id=10901, name="Power Word: Shield", subText="Rank 10", level=60, icon="Interface\\Icons\\Spell_Holy_PowerWordShield", school="Discipline", cost=46000, requiredIds={10900}},
		{id=10961, name="Prayer of Healing", subText="Rank 4", level=60, icon="Interface\\Icons\\Spell_Holy_PrayerOfHealing02", school="Holy", cost=46000, requiredIds={10960}},
		{id=27681, name="Prayer of Spirit", subText="Rank 1", level=60, icon="Interface\\Icons\\Spell_Holy_PrayerofSpirit", school="Discipline", cost=2300, requiredIds={27841}},
		{id=10955, name="Shackle Undead", subText="Rank 3", level=60, icon="Interface\\Icons\\Spell_Nature_Slow", school="Discipline", cost=46000, requiredIds={9485}},
		{id=19312, name="Shadowguard", subText="Rank 6", level=60, icon="Interface\\Icons\\Spell_Nature _LightningShield", school="Shadow", cost=2300},
		{id=19266, name="Touch of Weakness", subText="Rank 6", level=60, icon="Interface\\Icons\\Spell_ Shadow_DeadofNight", school="Shadow", cost=2070},
	},
}
