setfenv(1, WhatsTraining)

OverridenSpells["WARLOCK"] = {
}

ClassSpellsByLevel["WARLOCK"] = {
	[1] = {
		{id=348, name="Immolate", subText="Rank 1", level=1, icon="Interface\\Icons\\Spell_Fire_Immolation", school="Destruction", cost=10},
	},
	[4] = {
		{id=16321, name="Grimoire of Blood Pact", subText="Rank 1", level=4, icon="Interface\\Icons\\INV_Misc_Book_06", school="Demonology", cost=100, isTome=true},
		{id=172, name="Corruption", subText="Rank 1", level=4, icon="Interface\\Icons\\Spell_Shadow_AbominationExplosion", school="Affliction", cost=100},
		{id=702, name="Curse of Weakness", subText="", level=4, icon="Interface\\Icons\\Spell_Shadow_CurseOfMannoroth", school="Affliction", cost=100},
	},
	[6] = {
		{id=1454, name="Life Tap", subText="Rank 1", level=6, icon="Interface\\Icons\\Spell_Shadow_BurningSpirit", school="Affliction", cost=100},
		{id=695, name="Shadow Bolt", subText="Rank 2", level=6, icon="Interface\\Icons\\Spell_Shadow_ShadowBolt", school="Destruction", cost=100, requiredIds={686}},
	},
	[8] = {
		{id=16302, name="Grimoire of Firebolt", subText="Rank 2", level=8, icon="Interface\\Icons\\INV_Misc_Book_06", school="Demonology", cost=100, isTome=true},
		{id=980, name="Curse of Agony", subText="Rank 1", level=8, icon="Interface\\Icons\\Spell_Shadow_CurseOfSargeras", school="Affliction", cost=200},
		{id=5782, name="Fear", subText="Rank 1", level=8, icon="Interface\\Icons\\Spell_Shadow_Possession", school="Affliction", cost=200},
	},
	[10] = {
		{id=6201, name="Create Healthstone (Minor)", subText="", level=10, icon="Interface\\Icons\\INV_Stone_04", school="Demonology", cost=300, requiredIds={1120}},
		{id=696, name="Demon Armor", subText="Rank 2", level=10, icon="Interface\\Icons\\Spell_Shadow_RagingScream", school="Demonology", cost=300, requiredIds={687}},
		{id=1120, name="Drain Soul", subText="Rank 1", level=10, icon="Interface\\Icons\\Spell_Shadow_Haunting", school="Affliction", cost=300},
		{id=707, name="Immolate", subText="Rank 2", level=10, icon="Interface\\Icons\\Spell_Fire_Immolation", school="Destruction", cost=300, requiredIds={348}},
	},
	[12] = {
		{id=16331, name="Grimoire of Phase Shift", subText="", level=12, icon="Interface\\Icons\\INV_Misc_Book_06", school="Demonology", cost=600, isTome=true},
		{id=1108, name="Curse of Weakness", subText="Rank 2", level=12, icon="Interface\\Icons\\Spell_ Shadow_CurseOfMannoroth", school="Affliction", cost=600, requiredIds={702}},
		{id=755, name="Health Funnel", subText="Rank 1", level=12, icon="Interface\\Icons\\Spell_Shadow_LifeDrain", school="Demonology", cost=600},
		{id=705, name="Shadow Bolt", subText="Rank 3", level=12, icon="Interface\\Icons\\Spell_Shadow_ShadowBolt", school="Destruction", cost=600, requiredIds={695}},
	},
	[14] = {
		{id=16322, name="Grimoire of Blood Pact", subText="Rank 2", level=14, icon="Interface\\Icons\\INV_Misc_Book_06", school="Demonology", cost=900, isTome=true},
		{id=16326, name="Grimoire of Fire Shield", subText="Rank 1", level=14, icon="Interface\\Icons\\INV_Misc_Book_06", school="Demonology", cost=900, isTome=true},
		{id=6222, name="Corruption", subText="Rank 2", level=14, icon="Interface\\Icons\\Spell_Shadow_AbominationExplosion", school="Affliction", cost=900, requiredIds={172}},
		{id=704, name="Curse of Recklessness", subText="Rank 1", level=14, icon="Interface\\Icons\\Spell_Shadow_UnholyStrength", school="Affliction", cost=900},
		{id=689, name="Drain Life", subText="Rank 1", level=14, icon="Interface\\Icons\\Spell_Shadow_LifeDrain02", school="Affliction", cost=900},
	},
	[16] = {
		{id=16351, name="Grimoire of Sacrifice", subText="Rank 1", level=16, icon="Interface\\Icons\\INV_Misc_Book_06", school="Demonology", cost=1200, isTome=true},
		{id=1455, name="Life Tap", subText="Rank 2", level=16, icon="Interface\\Icons\\Spell_Shadow_BurningSpirit", school="Affliction", cost=1200, requiredIds={1454}},
		{id=5697, name="Unending Breath", subText="", level=16, icon="Interface\\Icons\\Spell_Shadow_DemonBreath", school="Demonology", cost=1200},
	},
	[18] = {
		{id=16316, name="Grimoire of Firebolt", subText="Rank 3", level=18, icon="Interface\\Icons\\INV_Misc_Book_06", school="Demonology", cost=1500, isTome=true},
		{id=16357, name="Grimoire of Consume Shadows", subText="Rank 1", level=18, icon="Interface\\Icons\\INV_Misc_Book_06", school="Demonology", cost=1500, isTome=true},
		{id=693, name="Create Soulstone (Minor)", subText="", level=18, icon="Interface\\Icons\\Spell_Shadow_SoulGem", school="Demonology", cost=1500, requiredIds={1120}},
		{id=1014, name="Curse of Agony", subText="Rank 2", level=18, icon="Interface\\Icons\\Spell_Sha dow_CurseOfSargeras", school="Affliction", cost=1500, requiredIds={980}},
		{id=5676, name="Searing Pain", subText="Rank 1", level=18, icon="Interface\\Icons\\Spell_Fire_SoulBurn", school="Destruction", cost=1500},
	},
	[20] = {
		{id=16346, name="Grimoire of Torment", subText="Rank 2", level=20, icon="Interface\\Icons\\INV_Misc_Book_06", school="Demonology", cost=2000, isTome=true},
		{id=706, name="Demon Armor", subText="Rank 3", level=20, icon="Interface\\Icons\\Spell_Shadow_RagingScream", school="Demonology", cost=2000},
		{id=3698, name="Health Funnel", subText="Rank 2", level=20, icon="Interface\\Icons\\Spell_Shadow_LifeDrain", school="Demonology", cost=2000, requiredIds={755}},
		{id=1094, name="Immolate", subText="Rank 3", level=20, icon="Interface\\Icons\\Spell_Fire_Immolation", school="Destruction", cost=2000, requiredIds={707}},
		{id=5740, name="Rain of Fire", subText="Rank 1", level=20, icon="Interface\\Icons\\Spell_Shadow_RainOfFire", school="Destruction", cost=2000},
		{id=698, name="Ritual of Summoning", subText="", level=20, icon="Interface\\Icons\\Spell_Shadow_Twilight", school="Demonology", cost=2000},
		{id=1088, name="Shadow Bolt", subText="Rank 4", level=20, icon="Interface\\Icons\\Spell_Shadow_ShadowBolt", school="Destruction", cost=2000, requiredIds={705}},
	},
	[22] = {
		{id=16375, name="Grimoire of Soothing Kiss", subText="Rank 1", level=22, icon="Interface\\Icons\\INV_Misc_Book_06", school="Demonology", cost=2500, isTome=true},
		{id=6202, name="Create Healthstone (Lesser)", subText="", level=22, icon="Interface\\Icons\\INV_Stone_04", school="Demonology", cost=2500, requiredIds={6201}},
		{id=6205, name="Curse of Weakness", subText="Rank 3", level=22, icon="Interface\\Icons\\Spell_ Shadow_CurseOfMannoroth", school="Affliction", cost=2500, requiredIds={1108}},
		{id=699, name="Drain Life", subText="Rank 2", level=22, icon="Interface\\Icons\\Spell_Shadow_LifeDrain02", school="Affliction", cost=2500, requiredIds={689}},
		{id=126, name="Eye of Kilrogg", subText="Summon", level=22, icon="Interface\\Icons\\Spell_Shadow_EvilEye", school="Demonology", cost=2500},
	},
	[24] = {
		{id=16327, name="Grimoire of Fire Shield", subText="Rank 2", level=24, icon="Interface\\Icons\\INV_Misc_Book_06", school="Demonology", cost=3000, isTome=true},
		{id=16352, name="Grimoire of Sacrifice", subText="Rank 2", level=24, icon="Interface\\Icons\\INV_Misc_Book_06", school="Demonology", cost=3000, isTome=true},
		{id=16363, name="Grimoire of Suffering", subText="Rank 1", level=24, icon="Interface\\Icons\\INV_Misc_Book_06", school="Demonology", cost=3000, isTome=true},
		{id=6223, name="Corruption", subText="Rank 3", level=24, icon="Interface\\Icons\\Spell_Shadow_AbominationExplosion", school="Affliction", cost=3000, requiredIds={6222}},
		{id=5138, name="Drain Mana", subText="Rank 1", level=24, icon="Interface\\Icons\\Spell_Shadow_SiphonMana", school="Affliction", cost=3000},
		{id=8288, name="Drain Soul", subText="Rank 2", level=24, icon="Interface\\Icons\\Spell_Shadow_Haunting", school="Affliction", cost=3000, requiredIds={1120}},
		{id=5500, name="Sense Demons", subText="", level=24, icon="Interface\\Icons\\Spell_Shadow_Metamorphosis", school="Demonology", cost=3000},
		{id=18867, name="Shadowburn", subText="Rank 2", level=24, icon="Interface\\Icons\\Spell_Shadow _ScourgeBuild", school="Affliction", cost=150, requiredTalent={name="Shadowburn", tabIndex=3}},
	},
	[26] = {
		{id=16323, name="Grimoire of Blood Pact", subText="Rank 3", level=26, icon="Interface\\Icons\\INV_Misc_Book_06", school="Demonology", cost=4000, isTome=true},
		{id=16358, name="Grimoire of Consume Shadows", subText="Rank 2", level=26, icon="Interface\\Icons\\INV_Misc_Book_06", school="Demonology", cost=4000, isTome=true},
		{id=16379, name="Grimoire of Seduction", subText="", level=26, icon="Interface\\Icons\\INV_Misc_Book_06", school="Demonology", cost=4000, isTome=true},
		{id=1714, name="Curse of Tongues", subText="Rank 1", level=26, icon="Interface\\Icons\\Spell_Shadow_CurseOfTounges", school="Affliction", cost=4000},
		{id=132, name="Detect Lesser Invisibility", subText="", level=26, icon="Interface\\Icons\\Spell_Shadow_DetectLesserInvisibility", school="Demonology", cost=4000},
		{id=1456, name="Life Tap", subText="Rank 3", level=26, icon="Interface\\Icons\\Spell_Shadow_BurningSpirit", school="Affliction", cost=4000, requiredIds={1455}},
		{id=17919, name="Searing Pain", subText="Rank 2", level=26, icon="Interface\\Icons\\Spell_Fire_SoulBurn", school="Destruction", cost=4000, requiredIds={5676}},
	},
	[28] = {
		{id=16317, name="Grimoire of Firebolt", subText="Rank 4", level=28, icon="Interface\\Icons\\INV_Misc_Book_06", school="Demonology", cost=5000, isTome=true},
		{id=16368, name="Grimoire of Lash of Pain", subText="Rank 2", level=28, icon="Interface\\Icons\\INV_Misc_Book_06", school="Demonology", cost=5000, isTome=true},
		{id=710, name="Banish", subText="Rank 1", level=28, icon="Interface\\Icons\\Spell_Shadow_Cripple", school="Demonology", cost=5000},
		{id=6366, name="Create Firestone (Lesser)", subText="", level=28, icon="Interface\\Icons\\INV_Ammo_FireTar", school="Demonology", cost=5000},
		{id=6217, name="Curse of Agony", subText="Rank 3", level=28, icon="Interface\\Icons\\Spell_Shadow_CurseOfSargeras", school="Affliction", cost=5000, requiredIds={1014}},
		{id=7658, name="Curse of Recklessness", subText="Rank 2", level=28, icon="Interface\\Icons\\Spell_Shadow_UnholyStrength", school="Affliction", cost=5000, requiredIds={704}},
		{id=3699, name="Health Funnel", subText="Rank 3", level=28, icon="Interface\\Icons\\Spell_Shadow_LifeDrain", school="Demonology", cost=5000, requiredIds={3698}},
		{id=1106, name="Shadow Bolt", subText="Rank 5", level=28, icon="Interface\\Icons\\Spell_Shadow_ShadowBolt", school="Destruction", cost=5000, requiredIds={1088}},
	},
	[30] = {
		{id=16347, name="Grimoire of Torment", subText="Rank 3", level=30, icon="Interface\\Icons\\INV_Misc_Book_06", school="Demonology", cost=6000, isTome=true},
		{id=20752, name="Create Soulstone (Lesser)", subText="", level=30, icon="Interface\\Icons\\Spell_Shadow_SoulGem", school="Demonology", cost=6000, requiredIds={693}},
		{id=1086, name="Demon Armor", subText="Rank 4", level=30, icon="Interface\\Icons\\Spell_Shadow_RagingScream", school="Demonology", cost=6000, requiredIds={706}},
		{id=709, name="Drain Life", subText="Rank 3", level=30, icon="Interface\\Icons\\Spell_Shadow_LifeDrain02", school="Affliction", cost=6000, requiredIds={699}},
		{id=1098, name="Enslave Demon", subText="Rank 1", level=30, icon="Interface\\Icons\\Spell_Shadow_EnslaveDemon", school="Demonology", cost=6000},
		{id=1949, name="Hellfire", subText="Rank 1", level=30, icon="Interface\\Icons\\Spell_Fire_Incinerate", school="Destruction", cost=6000},
		{id=2941, name="Immolate", subText="Rank 4", level=30, icon="Interface\\Icons\\Spell_Fire_Immolation", school="Destruction", cost=6000, requiredIds={1094}},
	},
	[32] = {
		{id=16353, name="Grimoire of Sacrifice", subText="Rank 3", level=32, icon="Interface\\Icons\\INV_Misc_Book_06", school="Demonology", cost=7000, isTome=true},
		{id=16380, name="Grimoire of Lesser Invisibility", subText="", level=32, icon="Interface\\Icons\\INV_Misc_Book_06", school="Demonology", cost=7000, isTome=true},
		{id=16384, name="Grimoire of Tainted Blood", subText="Rank 1", level=32, icon="Interface\\Icons\\INV_Misc_Book_06", school="Demonology", cost=7000, isTome=true},
		{id=7646, name="Curse of Weakness", subText="Rank 4", level=32, icon="Interface\\Icons\\Spell_ Shadow_CurseOfMannoroth", school="Affliction", cost=7000, requiredIds={6205}},
		{id=1490, name="Curse of the Elements", subText="Rank 1", level=32, icon="Interface\\Icons\\Spell_Shadow_ChillTouch", school="Affliction", cost=7000},
		{id=6213, name="Fear", subText="Rank 2", level=32, icon="Interface\\Icons\\Spell_Shadow_Possession", school="Affliction", cost=7000, requiredIds={5782}},
		{id=6229, name="Shadow Ward", subText="Rank 1", level=32, icon="Interface\\Icons\\Spell_Shadow_AntiShadow", school="Demonology", cost=7000},
	},
	[34] = {
		{id=16328, name="Grimoire of Fire Shield", subText="Rank 3", level=34, icon="Interface\\Icons\\INV_Misc_Book_06", school="Demonology", cost=8000, isTome=true},
		{id=16359, name="Grimoire of Consume Shadows", subText="Rank 3", level=34, icon="Interface\\Icons\\INV_Misc_Book_06", school="Demonology", cost=8000, isTome=true},
		{id=16376, name="Grimoire of Soothing Kiss", subText="Rank 2", level=34, icon="Interface\\Icons\\INV_Misc_Book_06", school="Demonology", cost=8000, isTome=true},
		{id=7648, name="Corruption", subText="Rank 4", level=34, icon="Interface\\Icons\\Spell_Shadow_AbominationExplosion", school="Affliction", cost=8000, requiredIds={6223}},
		{id=5699, name="Create Healthstone", subText="", level=34, icon="Interface\\Icons\\INV_Stone_04", school="Demonology", cost=8000, requiredIds={6202}},
		{id=6226, name="Drain Mana", subText="Rank 2", level=34, icon="Interface\\Icons\\Spell_Shadow_SiphonMana", school="Affliction", cost=8000, requiredIds={5138}},
		{id=6219, name="Rain of Fire", subText="Rank 2", level=34, icon="Interface\\Icons\\Spell_Shadow_RainOfFire", school="Destruction", cost=8000, requiredIds={5740}},
		{id=17920, name="Searing Pain", subText="Rank 3", level=34, icon="Interface\\Icons\\Spell_Fire_SoulBurn", school="Destruction", cost=8000, requiredIds={17919}},
	},
	[36] = {
		{id=16364, name="Grimoire of Suffering", subText="Rank 2", level=36, icon="Interface\\Icons\\INV_Misc_Book_06", school="Demonology", cost=9000, isTome=true},
		{id=16371, name="Grimoire of Lash of Pain", subText="Rank 3", level=36, icon="Interface\\Icons\\INV_Misc_Book_06", school="Demonology", cost=9000, isTome=true},
		{id=16388, name="Grimoire of Spell Lock", subText="Rank 1", level=36, icon="Interface\\Icons\\INV_Misc_Book_06", school="Demonology", cost=9000, isTome=true},
		{id=17951, name="Create Firestone", subText="", level=36, icon="Interface\\Icons\\INV_Ammo_FireTar", school="Demonology", cost=9000, requiredIds={6366}},
		{id=2362, name="Create Spellstone", subText="", level=36, icon="Interface\\Icons\\INV_Misc_Gem_Sapphire_01", school="Demonology", cost=9000, requiredIds={1120}},
		{id=3700, name="Health Funnel", subText="Rank 4", level=36, icon="Interface\\Icons\\Spell_Shadow_LifeDrain", school="Demonology", cost=9000, requiredIds={3699}},
		{id=11687, name="Life Tap", subText="Rank 4", level=36, icon="Interface\\Icons\\Spell_Shadow_BurningSpirit", school="Affliction", cost=9000, requiredIds={1456}},
		{id=7641, name="Shadow Bolt", subText="Rank 6", level=36, icon="Interface\\Icons\\Spell_Shadow_ShadowBolt", school="Destruction", cost=9000, requiredIds={1106}},
	},
	[38] = {
		{id=16318, name="Grimoire of Firebolt", subText="Rank 5", level=38, icon="Interface\\Icons\\INV_Misc_Book_06", school="Demonology", cost=10000, isTome=true},
		{id=16324, name="Grimoire of Blood Pact", subText="Rank 4", level=38, icon="Interface\\Icons\\INV_Misc_Book_06", school="Demonology", cost=10000, isTome=true},
		{id=16381, name="Grimoire of Devour Magic", subText="Rank 2", level=38, icon="Interface\\Icons\\INV_Misc_Book_06", school="Demonology", cost=10000, isTome=true},
		{id=11711, name="Curse of Agony", subText="Rank 4", level=38, icon="Interface\\Icons\\Spell_Shadow_CurseOfSargeras", school="Affliction", cost=10000, requiredIds={6217}},
		{id=2970, name="Detect Invisibility", subText="", level=38, icon="Interface\\Icons\\Spell_Shadow_DetectInvisibility", school="Demonology", cost=10000, requiredIds={132}},
		{id=7651, name="Drain Life", subText="Rank 4", level=38, icon="Interface\\Icons\\Spell_Shadow_LifeDrain02", school="Affliction", cost=10000, requiredIds={709}},
		{id=8289, name="Drain Soul", subText="Rank 3", level=38, icon="Interface\\Icons\\Spell_Shadow_Haunting", school="Affliction", cost=10000, requiredIds={8288}},
		{id=18879, name="Siphon Life", subText="Rank 2", level=38, icon="Interface\\Icons\\Spell_Shado w_Requiem", school="Affliction", cost=500, requiredTalent={name="Siphon Life", tabIndex=1}},
	},
	[40] = {
		{id=16348, name="Grimoire of Torment", subText="Rank 4", level=40, icon="Interface\\Icons\\INV_Misc_Book_06", school="Demonology", cost=11000, isTome=true},
		{id=16354, name="Grimoire of Sacrifice", subText="Rank 4", level=40, icon="Interface\\Icons\\INV_Misc_Book_06", school="Demonology", cost=11000, isTome=true},
		{id=16385, name="Grimoire of Tainted Blood", subText="Rank 2", level=40, icon="Interface\\Icons\\INV_Misc_Book_06", school="Demonology", cost=11000, isTome=true},
		{id=20755, name="Create Soulstone", subText="", level=40, icon="Interface\\Icons\\Spell_Shadow_SoulGem", school="Demonology", cost=11000, requiredIds={20752}},
		{id=11733, name="Demon Armor", subText="Rank 5", level=40, icon="Interface\\Icons\\Spell_Shadow_RagingScream", school="Demonology", cost=11000, requiredIds={1086}},
		{id=5484, name="Howl of Terror", subText="Rank 1", level=40, icon="Interface\\Icons\\Spell_Shadow_DeathScream", school="Affliction", cost=11000},
		{id=11665, name="Immolate", subText="Rank 5", level=40, icon="Interface\\Icons\\Spell_Fire_Immolation", school="Destruction", cost=11000, requiredIds={2941}},
	},
	[42] = {
		{id=16360, name="Grimoire of Consume Shadows", subText="Rank 4", level=42, icon="Interface\\Icons\\INV_Misc_Book_06", school="Demonology", cost=11000, isTome=true},
		{id=16390, name="Grimoire of Paranoia", subText="", level=42, icon="Interface\\Icons\\INV_Misc_Book_06", school="Demonology", cost=11000, isTome=true},
		{id=7659, name="Curse of Recklessness", subText="Rank 3", level=42, icon="Interface\\Icons\\Spell_Shadow_UnholyStrength", school="Affliction", cost=11000, requiredIds={7658}},
		{id=11707, name="Curse of Weakness", subText="Rank 5", level=42, icon="Interface\\Icons\\Spell _Shadow_CurseOfMannoroth", school="Affliction", cost=11000, requiredIds={7646}},
		{id=6789, name="Death Coil", subText="Rank 1", level=42, icon="Interface\\Icons\\Spell_Shadow_DeathCoil", school="Affliction", cost=11000},
		{id=11683, name="Hellfire", subText="Rank 2", level=42, icon="Interface\\Icons\\Spell_Fire_Incinerate", school="Destruction", cost=9900, requiredIds={1949}},
		{id=17921, name="Searing Pain", subText="Rank 4", level=42, icon="Interface\\Icons\\Spell_Fire_SoulBurn", school="Destruction", cost=11000, requiredIds={17920}},
		{id=11739, name="Shadow Ward", subText="Rank 2", level=42, icon="Interface\\Icons\\Spell_Shadow_AntiShadow", school="Demonology", cost=11000, requiredIds={6229}},
	},
	[44] = {
		{id=16329, name="Grimoire of Fire Shield", subText="Rank 4", level=44, icon="Interface\\Icons\\INV_Misc_Book_06", school="Demonology", cost=12000, isTome=true},
		{id=16372, name="Grimoire of Lash of Pain", subText="Rank 4", level=44, icon="Interface\\Icons\\INV_Misc_Book_06", school="Demonology", cost=12000, isTome=true},
		{id=11671, name="Corruption", subText="Rank 5", level=44, icon="Interface\\Icons\\Spell_Shadow_AbominationExplosion", school="Affliction", cost=12000, requiredIds={7648}},
		{id=17862, name="Curse of Shadow", subText="Rank 1", level=44, icon="Interface\\Icons\\Spell_Shadow_CurseOfAchimonde", school="Affliction", cost=12000},
		{id=11703, name="Drain Mana", subText="Rank 3", level=44, icon="Interface\\Icons\\Spell_Shadow_SiphonMana", school="Affliction", cost=12000, requiredIds={6226}},
		{id=11725, name="Enslave Demon", subText="Rank 2", level=44, icon="Interface\\Icons\\Spell_Shadow_EnslaveDemon", school="Demonology", cost=12000, requiredIds={1098}},
		{id=11693, name="Health Funnel", subText="Rank 5", level=44, icon="Interface\\Icons\\Spell_Shadow_LifeDrain", school="Demonology", cost=12000, requiredIds={3700}},
		{id=11659, name="Shadow Bolt", subText="Rank 7", level=44, icon="Interface\\Icons\\Spell_Shadow_ShadowBolt", school="Destruction", cost=12000, requiredIds={7641}},
	},
	[46] = {
		{id=16377, name="Grimoire of Soothing Kiss", subText="Rank 3", level=46, icon="Interface\\Icons\\INV_Misc_Book_06", school="Demonology", cost=13000, isTome=true},
		{id=16382, name="Grimoire of Devour Magic", subText="Rank 3", level=46, icon="Interface\\Icons\\INV_Misc_Book_06", school="Demonology", cost=13000, isTome=true},
		{id=17952, name="Create Firestone (Greater)", subText="", level=46, icon="Interface\\Icons\\INV_Ammo_FireTar", school="Demonology", cost=13000, requiredIds={17951}},
		{id=11729, name="Create Healthstone (Greater)", subText="", level=46, icon="Interface\\Icons\\INV_Stone_04", school="Demonology", cost=13000, requiredIds={5699}},
		{id=11721, name="Curse of the Elements", subText="Rank 2", level=46, icon="Interface\\Icons\\Spell_Shadow_ChillTouch", school="Affliction", cost=13000, requiredIds={1490}},
		{id=11699, name="Drain Life", subText="Rank 5", level=46, icon="Interface\\Icons\\Spell_Shadow_LifeDrain02", school="Affliction", cost=13000, requiredIds={7651}},
		{id=11688, name="Life Tap", subText="Rank 5", level=46, icon="Interface\\Icons\\Spell_Shadow_BurningSpirit", school="Affliction", cost=13000, requiredIds={11687}},
		{id=11677, name="Rain of Fire", subText="Rank 3", level=46, icon="Interface\\Icons\\Spell_Shadow_RainOfFire", school="Destruction", cost=13000, requiredIds={6219}},
	},
	[48] = {
		{id=16319, name="Grimoire of Firebolt", subText="Rank 6", level=48, icon="Interface\\Icons\\INV_Misc_Book_06", school="Demonology", cost=14000, isTome=true},
		{id=16355, name="Grimoire of Sacrifice", subText="Rank 5", level=48, icon="Interface\\Icons\\INV_Misc_Book_06", school="Demonology", cost=14000, isTome=true},
		{id=16365, name="Grimoire of Suffering", subText="Rank 3", level=48, icon="Interface\\Icons\\INV_Misc_Book_06", school="Demonology", cost=14000, isTome=true},
		{id=16386, name="Grimoire of Tainted Blood", subText="Rank 3", level=48, icon="Interface\\Icons\\INV_Misc_Book_06", school="Demonology", cost=14000, isTome=true},
		{id=18647, name="Banish", subText="Rank 2", level=48, icon="Interface\\Icons\\Spell_Shadow_Cripple", school="Demonology", cost=13000, requiredIds={710}},
		{id=18930, name="Conflagrate", subText="Rank 2", level=48, icon="Interface\\Icons\\Spell_Fire_ Fireball", school="Destruction", cost=700, requiredTalent={name="Conflagrate", tabIndex=1}},
		{id=17727, name="Create Spellstone (Greater)", subText="", level=48, icon="Interface\\Icons\\INV_Misc_Gem_Sapphire_01", school="Demonology", cost=14000, requiredIds={2362}},
		{id=11712, name="Curse of Agony", subText="Rank 5", level=48, icon="Interface\\Icons\\Spell_Shadow_CurseOfSargeras", school="Affliction", cost=14000, requiredIds={11711}},
		{id=6353, name="Soul Fire", subText="Rank 1", level=48, icon="Interface\\Icons\\Spell_Fire_Fireball02", school="Destruction", cost=14000},
	},
	[50] = {
		{id=16325, name="Grimoire of Blood Pact", subText="Rank 5", level=50, icon="Interface\\Icons\\INV_Misc_Book_06", school="Demonology", cost=15000, isTome=true},
		{id=16349, name="Grimoire of Torment", subText="Rank 5", level=50, icon="Interface\\Icons\\INV_Misc_Book_06", school="Demonology", cost=15000, isTome=true},
		{id=16361, name="Grimoire of Consume Shadows", subText="Rank 5", level=50, icon="Interface\\Icons\\INV_Misc_Book_06", school="Demonology", cost=15000, isTome=true},
		{id=20756, name="Create Soulstone (Greater)", subText="", level=50, icon="Interface\\Icons\\Spell_Shadow_SoulGem", school="Demonology", cost=15000, requiredIds={20755}},
		{id=11719, name="Curse of Tongues", subText="Rank 2", level=50, icon="Interface\\Icons\\Spell_Shadow_CurseOfTounges", school="Affliction", cost=15000, requiredIds={1714}},
		{id=18937, name="Dark Pact", subText="Rank 2", level=50, icon="Interface\\Icons\\Spell_Shadow_DarkRitual", school="Affliction", cost=750, requiredTalent={name="Dark Pact", tabIndex=2}},
		{id=17925, name="Death Coil", subText="Rank 2", level=50, icon="Interface\\Icons\\Spell_Shadow_DeathCoil", school="Affliction", cost=15000, requiredIds={6789}},
		{id=11734, name="Demon Armor", subText="Rank 6", level=50, icon="Interface\\Icons\\Spell_Shadow_RagingScream", school="Demonology", cost=15000, requiredIds={11733}},
		{id=11743, name="Detect Greater Invisibility", subText="", level=50, icon="Interface\\Icons\\Spell_Shadow_DetectInvisibility", school="Demonology", cost=15000, requiredIds={2970}},
		{id=11667, name="Immolate", subText="Rank 6", level=50, icon="Interface\\Icons\\Spell_Fire_Immolation", school="Destruction", cost=15000, requiredIds={11665}},
		{id=17922, name="Searing Pain", subText="Rank 5", level=50, icon="Interface\\Icons\\Spell_Fire_SoulBurn", school="Destruction", cost=15000, requiredIds={17921}},
	},
	[52] = {
		{id=16373, name="Grimoire of Lash of Pain", subText="Rank 5", level=52, icon="Interface\\Icons\\INV_Misc_Book_06", school="Demonology", cost=18000, isTome=true},
		{id=16389, name="Grimoire of Spell Lock", subText="Rank 2", level=52, icon="Interface\\Icons\\INV_Misc_Book_06", school="Demonology", cost=18000, isTome=true},
		{id=11708, name="Curse of Weakness", subText="Rank 6", level=52, icon="Interface\\Icons\\Spell _Shadow_CurseOfMannoroth", school="Affliction", cost=18000, requiredIds={11707}},
		{id=11675, name="Drain Soul", subText="Rank 4", level=52, icon="Interface\\Icons\\Spell_Shadow_Haunting", school="Affliction", cost=18000, requiredIds={8289}},
		{id=11694, name="Health Funnel", subText="Rank 6", level=52, icon="Interface\\Icons\\Spell_Shadow_LifeDrain", school="Demonology", cost=18000, requiredIds={11693}},
		{id=11660, name="Shadow Bolt", subText="Rank 8", level=52, icon="Interface\\Icons\\Spell_Shadow_ShadowBolt", school="Destruction", cost=18000, requiredIds={11659}},
		{id=11740, name="Shadow Ward", subText="Rank 3", level=52, icon="Interface\\Icons\\Spell_Shadow_AntiShadow", school="Demonology", cost=18000, requiredIds={11739}},
	},
	[54] = {
		{id=16330, name="Grimoire of Fire Shield", subText="Rank 5", level=54, icon="Interface\\Icons\\INV_Misc_Book_06", school="Demonology", cost=20000, isTome=true},
		{id=16383, name="Grimoire of Devour Magic", subText="Rank 4", level=54, icon="Interface\\Icons\\INV_Misc_Book_06", school="Demonology", cost=20000, isTome=true},
		{id=11672, name="Corruption", subText="Rank 6", level=54, icon="Interface\\Icons\\Spell_Shadow_AbominationExplosion", school="Affliction", cost=20000, requiredIds={11671}},
		{id=11700, name="Drain Life", subText="Rank 6", level=54, icon="Interface\\Icons\\Spell_Shadow_LifeDrain02", school="Affliction", cost=20000, requiredIds={11699}},
		{id=11704, name="Drain Mana", subText="Rank 4", level=54, icon="Interface\\Icons\\Spell_Shadow_SiphonMana", school="Affliction", cost=20000, requiredIds={11703}},
		{id=11684, name="Hellfire", subText="Rank 3", level=54, icon="Interface\\Icons\\Spell_Fire_Incinerate", school="Destruction", cost=18000, requiredIds={11683}},
		{id=17928, name="Howl of Terror", subText="Rank 2", level=54, icon="Interface\\Icons\\Spell_Shadow_DeathScream", school="Affliction", cost=20000, requiredIds={5484}},
	},
	[56] = {
		{id=16356, name="Grimoire of Sacrifice", subText="Rank 6", level=56, icon="Interface\\Icons\\INV_Misc_Book_06", school="Demonology", cost=22000, isTome=true},
		{id=16387, name="Grimoire of Tainted Blood", subText="Rank 4", level=56, icon="Interface\\Icons\\INV_Misc_Book_06", school="Demonology", cost=22000, isTome=true},
		{id=17953, name="Create Firestone (Major)", subText="", level=56, icon="Interface\\Icons\\INV_Ammo_FireTar", school="Demonology", cost=22000, requiredIds={17952}},
		{id=11717, name="Curse of Recklessness", subText="Rank 4", level=56, icon="Interface\\Icons\\Spell_Shadow_UnholyStrength", school="Affliction", cost=22000, requiredIds={7659}},
		{id=17937, name="Curse of Shadow", subText="Rank 2", level=56, icon="Interface\\Icons\\Spell_Shadow_CurseOfAchimonde", school="Affliction", cost=22000, requiredIds={17862}},
		{id=6215, name="Fear", subText="Rank 3", level=56, icon="Interface\\Icons\\Spell_Shadow_Possession", school="Affliction", cost=22000, requiredIds={6213}},
		{id=11689, name="Life Tap", subText="Rank 6", level=56, icon="Interface\\Icons\\Spell_Shadow_BurningSpirit", school="Affliction", cost=22000, requiredIds={11688}},
		{id=17924, name="Soul Fire", subText="Rank 2", level=56, icon="Interface\\Icons\\Spell_Fire_Fireball02", school="Destruction", cost=22000, requiredIds={6353}},
	},
	[58] = {
		{id=16320, name="Grimoire of Firebolt", subText="Rank 7", level=58, icon="Interface\\Icons\\INV_Misc_Book_06", school="Demonology", cost=24000, isTome=true},
		{id=16362, name="Grimoire of Consume Shadows", subText="Rank 6", level=58, icon="Interface\\Icons\\INV_Misc_Book_06", school="Demonology", cost=24000, isTome=true},
		{id=16378, name="Grimoire of Soothing Kiss", subText="Rank 4", level=58, icon="Interface\\Icons\\INV_Misc_Book_06", school="Demonology", cost=24000, isTome=true},
		{id=11730, name="Create Healthstone (Major)", subText="", level=58, icon="Interface\\Icons\\INV_Stone_04", school="Demonology", cost=24000, requiredIds={11730}},
		{id=11713, name="Curse of Agony", subText="Rank 6", level=58, icon="Interface\\Icons\\Spell_Shadow_CurseOfSargeras", school="Affliction", cost=24000, requiredIds={11712}},
		{id=17926, name="Death Coil", subText="Rank 3", level=58, icon="Interface\\Icons\\Spell_Shadow_DeathCoil", school="Affliction", cost=24000, requiredIds={17925}},
		{id=11726, name="Enslave Demon", subText="Rank 3", level=58, icon="Interface\\Icons\\Spell_Shadow_EnslaveDemon", school="Demonology", cost=24000, requiredIds={11725}},
		{id=11678, name="Rain of Fire", subText="Rank 4", level=58, icon="Interface\\Icons\\Spell_Shadow_RainOfFire", school="Destruction", cost=24000, requiredIds={11677}},
		{id=17923, name="Searing Pain", subText="Rank 6", level=58, icon="Interface\\Icons\\Spell_Fire_SoulBurn", school="Destruction", cost=24000, requiredIds={17922}},
	},
	[60] = {
		{id=16350, name="Grimoire of Torment", subText="Rank 6", level=60, icon="Interface\\Icons\\INV_Misc_Book_06", school="Demonology", cost=26000, isTome=true},
		{id=16366, name="Grimoire of Suffering", subText="Rank 4", level=60, icon="Interface\\Icons\\INV_Misc_Book_06", school="Demonology", cost=26000, isTome=true},
		{id=16374, name="Grimoire of Lash of Pain", subText="Rank 6", level=60, icon="Interface\\Icons\\INV_Misc_Book_06", school="Demonology", cost=26000, isTome=true},
		{id=20757, name="Create Soulstone (Major)", subText="", level=60, icon="Interface\\Icons\\Spell_Shadow_SoulGem", school="Demonology", cost=26000, requiredIds={20756}},
		{id=17728, name="Create Spellstone (Major)", subText="", level=60, icon="Interface\\Icons\\INV_Misc_Gem_Sapphire_01", school="Demonology", cost=26000, requiredIds={17727}},
		{id=603, name="Curse of Doom", subText="", level=60, icon="Interface\\Icons\\Spell_Shadow_AuraOfDarkness", school="Affliction", cost=26000},
		{id=11722, name="Curse of the Elements", subText="Rank 3", level=60, icon="Interface\\Icons\\Spell_Shadow_ChillTouch", school="Affliction", cost=26000, requiredIds={11721}},
		{id=18938, name="Dark Pact", subText="Rank 3", level=60, icon="Interface\\Icons\\Spell_Shadow_DarkRitual", school="Affliction", cost=1300, requiredIds={18937}, requiredTalent={name="Dark Pact", tabIndex=2}},
		{id=11735, name="Demon Armor", subText="Rank 7", level=60, icon="Interface\\Icons\\Spell_Shadow_RagingScream", school="Demonology", cost=26000, requiredIds={11734}},
		{id=11695, name="Health Funnel", subText="Rank 7", level=60, icon="Interface\\Icons\\Spell_Shadow_LifeDrain", school="Demonology", cost=26000, requiredIds={11694}},
		{id=11668, name="Immolate", subText="Rank 7", level=60, icon="Interface\\Icons\\Spell_Fire_Immolation", school="Destruction", cost=26000, requiredIds={11667}},
		{id=11661, name="Shadow Bolt", subText="Rank 9", level=60, icon="Interface\\Icons\\Spell_Shadow_ShadowBolt", school="Destruction", cost=26000, requiredIds={11660}},
	},
}
